import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn,execFileSync} from 'node:child_process';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {once} from 'node:events';
import {DatabaseSync} from 'node:sqlite';
const cwd=process.cwd(),data=mkdtempSync(join(tmpdir(),'sf-test-')),port=31000+Math.floor(Math.random()*10000),origin=`http://localhost:${port}`,env={...process.env,DATA_DIR:data,PORT:String(port),APP_ORIGIN:origin,ADMIN_EMAIL:'owner@example.test',ADMIN_PASSWORD:'long-test-password-123',ADMIN_NAME:'Test Owner'};
let child;
async function start(){child=spawn(process.execPath,['src/server.mjs'],{cwd,env,stdio:['ignore','pipe','pipe']});let errors='';child.stderr.on('data',d=>errors+=d);await Promise.race([once(child.stdout,'data'),new Promise((_,reject)=>child.once('exit',c=>reject(Error('Server failed: '+c+errors))))]);}
async function call(path,method='GET',body,session={},extra={}){if(path==='/api/photos'&&method==='POST')body={date:'2000-01-02',place:'Test location',description:'Test family memory',outsiders:'Test guest',...body};const res=await fetch(origin+path,{method,headers:{origin,'content-type':'application/json',...(session.cookie?{cookie:session.cookie}:{}),...(session.csrf?{'x-csrf-token':session.csrf}:{}),...extra},...(body?{body:JSON.stringify(body)}:{})});let payload;const type=res.headers.get('content-type')||'';if(type.includes('json'))payload=await res.json();else payload=await res.arrayBuffer();return{status:res.status,body:payload,cookie:res.headers.get('set-cookie')?.split(';')[0],csrf:payload?.csrf};}
test('real server: invitations, permissions, moderation, persistence and scale',async t=>{
 execFileSync(process.execPath,['src/admin.mjs'],{cwd,env,stdio:'pipe'});await start();t.after(async()=>{if(child&&!child.killed){child.kill();await once(child,'exit');}rmSync(data,{recursive:true,force:true});});
 let owner,member,mod,p1,p2,photoId;
 await t.test('anonymous access and origin protection',async()=>{assert.equal((await call('/api/bootstrap')).status,401);assert.equal((await call('/api/login','POST',{email:env.ADMIN_EMAIL,password:env.ADMIN_PASSWORD},{},{origin:'https://evil.example'})).status,403);});
 await t.test('login and CSRF enforcement',async()=>{owner=await call('/api/login','POST',{email:env.ADMIN_EMAIL,password:env.ADMIN_PASSWORD});assert.equal(owner.status,200);assert.ok(owner.cookie);assert.equal((await call('/api/people','POST',{name:'Blocked'},{cookie:owner.cookie})).status,403);});
 await t.test('owner creates people and real relations',async()=>{p1=await call('/api/people','POST',{name:'Parent One',birthDate:'1960-01-01',country:'Türkiye'},owner);assert.equal(p1.status,201);p2=await call('/api/people','POST',{name:'Child Two',birthDate:'1990-01-01'},owner);assert.equal(p2.status,201);assert.equal((await call('/api/relations','POST',{personA:p1.body.id,personB:p2.body.id,type:'parent'},owner)).status,201);assert.equal((await call('/api/relations','POST',{personA:p2.body.id,personB:p1.body.id,type:'parent'},owner)).status,400);});
 await t.test('single-use invitations bind recipient and role',async()=>{const invite=await call('/api/invites','POST',{email:'member@example.test',role:'member'},owner);assert.equal(invite.status,201);const token=invite.body.url.split('=')[1];member=await call('/api/accept-invite','POST',{token,name:'Member',password:'member-long-password',role:'owner'});assert.equal(member.status,201);assert.equal(member.body.user.role,'member');assert.equal((await call('/api/accept-invite','POST',{token,name:'Other',password:'other-long-password'})).status,400);const mi=await call('/api/invites','POST',{email:'mod@example.test',role:'moderator'},owner);mod=await call('/api/accept-invite','POST',{token:mi.body.url.split('=')[1],name:'Moderator',password:'moderator-long-pass'});assert.equal(mod.status,201);});
 await t.test('role enforcement',async()=>{assert.equal((await call('/api/people','POST',{name:'Forbidden'},member)).status,403);assert.equal((await call('/api/admin','GET',null,member)).status,403);assert.equal((await call('/api/invites','POST',{email:'fake@example.test',role:'moderator'},mod)).status,403);assert.equal((await call('/api/settings','PATCH',{familyTitle:'Wrong'},mod)).status,403);});
 await t.test('private media, moderation, person tags and SVG rejection',async()=>{const png='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+j5qkAAAAASUVORK5CYII=';const upload=await call('/api/photos','POST',{title:'Family photo',data:png,peopleIds:[p1.body.id]},member);assert.equal(upload.status,201);photoId=upload.body.id;assert.equal(upload.body.status,'pending');assert.equal((await call('/media/'+photoId)).status,401);assert.equal((await call('/api/photos/'+photoId,'PATCH',{status:'approved'},member)).status,403);assert.equal((await call('/api/photos/'+photoId,'PATCH',{status:'approved'},mod)).status,200);const bootstrap=await call('/api/bootstrap','GET',null,member);assert.deepEqual(bootstrap.body.photos[0].peopleIds,[p1.body.id]);assert.equal((await call('/media/'+photoId,'GET',null,member)).status,200);assert.equal((await call('/api/photos','POST',{title:'SVG injection',data:Buffer.from('<svg onload="alert(1)"></svg>').toString('base64')},member)).status,400);});
 await t.test('member edits return to moderation',async()=>{const e=await call('/api/events','POST',{title:'Family meetup',date:'2027-01-01',type:'gathering',personId:p1.body.id},member);assert.equal(e.status,201);assert.equal((await call('/api/events/'+e.body.id,'PATCH',{status:'approved'},mod)).status,200);assert.equal((await call('/api/events/'+e.body.id,'PATCH',{title:'Updated',date:'2027-02-01'},member)).status,200);const b=await call('/api/bootstrap','GET',null,owner);assert.equal(b.body.events.find(x=>x.id===e.body.id).status,'pending');});
 await t.test('soft-delete and restore retain relationships',async()=>{assert.equal((await call('/api/people/'+p2.body.id,'DELETE',{},mod)).status,200);let b=await call('/api/bootstrap','GET',null,owner);assert.ok(!b.body.people.some(x=>x.id===p2.body.id));assert.equal(b.body.relations.length,0);assert.equal((await call('/api/restore','POST',{table:'people',id:p2.body.id},mod)).status,200);b=await call('/api/bootstrap','GET',null,owner);assert.equal(b.body.relations.length,1);});
 await t.test('1200 people and 50 concurrent authenticated reads',async()=>{const db=new DatabaseSync(join(data,'family.sqlite'));db.exec('BEGIN');const insert=db.prepare('INSERT INTO people(id,name,createdAt,updatedAt) VALUES(?,?,?,?)');for(let i=0;i<1200;i++)insert.run('load-'+i,'Test Person '+i,new Date().toISOString(),new Date().toISOString());db.exec('COMMIT');db.close();const start=performance.now();const responses=await Promise.all(Array.from({length:50},()=>call('/api/bootstrap','GET',null,owner)));assert.ok(responses.every(r=>r.status===200&&r.body.people.length===1202));console.log('Load fixture: 1202 people; 50 concurrent reads; elapsed '+Math.round(performance.now()-start)+'ms');});
 await t.test('restart preserves data and sessions',async()=>{child.kill();await once(child,'exit');await start();const b=await call('/api/bootstrap','GET',null,owner);assert.equal(b.status,200);assert.equal(b.body.people.length,1202);assert.ok(b.body.photos.some(p=>p.id===photoId));});
 await t.test('role changes revoke sessions; resets are single-use',async()=>{const userId=member.body.user.id;assert.equal((await call('/api/users/'+userId,'PATCH',{role:'member',active:0},owner)).status,200);assert.equal((await call('/api/me','GET',null,member)).status,401);await call('/api/users/'+userId,'PATCH',{role:'member',active:1},owner);const r=await call('/api/reset-link','POST',{userId},owner);assert.equal(r.status,201);const token=r.body.url.split('=')[1];assert.equal((await call('/api/reset-password','POST',{token,password:'new-member-password'})).status,200);assert.equal((await call('/api/reset-password','POST',{token,password:'another-long-password'})).status,400);const session=await call('/api/login','POST',{email:'member@example.test',password:'new-member-password'});assert.equal(session.status,200);await call('/api/logout','POST',{},session);assert.equal((await call('/api/me','GET',null,session)).status,401);});
});
