import test from 'node:test';import assert from 'node:assert/strict';import{DatabaseSync}from'node:sqlite';import{readFileSync,readdirSync}from'node:fs';import worker from '../worker/index.mjs';import {totp,base32} from '../src/security.mjs';
function fixture(){const db=new DatabaseSync(':memory:');db.exec('PRAGMA foreign_keys=ON');for(const f of readdirSync('drizzle').filter(x=>x.endsWith('.sql')).sort())db.exec(readFileSync('drizzle/'+f,'utf8'));const files=new Map(),env={OWNER_EMAIL:'owner@test.invalid',CSRF_SECRET:'fixture-encryption-key',DB:{prepare(sql){const s={args:[],bind(...args){s.args=args;return s;},async first(){return db.prepare(sql).get(...s.args)||null;},async all(){return{results:db.prepare(sql).all(...s.args)};},async run(){return{meta:{changes:db.prepare(sql).run(...s.args).changes}};}};return s;},async batch(ss){db.exec('BEGIN');try{const out=[];for(const s of ss)out.push(await s.run());db.exec('COMMIT');return out;}catch(e){db.exec('ROLLBACK');throw e;}}},BUCKET:{async put(k,b){files.set(k,new Uint8Array(b));},async get(k){return files.has(k)?{body:files.get(k)}:null;},async delete(k){files.delete(k);}}};const csrf=new Map();async function call(path,method='GET',data,email='owner@test.invalid',factor=''){if(path==='/api/photos'&&method==='POST')data={date:'2000-01-02',place:'Test location',description:'Test family memory',outsiders:'Test guest',...data};const headers={'Content-Type':'application/json',Origin:'https://family.test','oai-authenticated-user-id':email,'oai-authenticated-user-email':email,'X-CSRF-Token':csrf.get(email)||'','X-Family-Factor':factor};const res=await worker.fetch(new Request('https://family.test'+path,{method,headers,...(data?{body:JSON.stringify(data)}:{})}),env);const type=res.headers.get('Content-Type'),body=type?.includes('json')?await res.json():await res.arrayBuffer();if(body.csrf)csrf.set(email,body.csrf);return{status:res.status,body};}async function member(email){await call('/api/me');const inv=await call('/api/invites','POST',{email,role:'member'});await call('/api/me','GET',null,email);return(await call('/api/accept-invite','POST',{name:email,token:inv.body.url.split('#invite=')[1]},email)).body.user;}return{db,files,env,call,member};}
const png='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a5L8AAAAASUVORK5CYII=';
test('Konak search includes untagged posts, folds Turkish and preserves privacy and literal wildcards',async()=>{
 const {call,member}=fixture();const a=await member('a@test.invalid');
 const make=async body=>(await call('/api/experience/feed','POST',{clientId:crypto.randomUUID(),...body})).body.id;
 const publicId=await make({body:'Fıstık bahçesi %100 aile',visibility:'family'});await make({body:'Fıstık özel kayıt',visibility:'private'});
 const found=await call('/api/experience/feed?q=fistik','GET',null,a.email);assert.equal(found.status,200);assert.deepEqual(found.body.items.map(p=>p.id),[publicId]);
 assert.equal((await call('/api/experience/feed?q=%25100','GET',null,a.email)).body.items.length,1);
 assert.equal((await call('/api/experience/feed?q=_','GET',null,a.email)).body.items.length,0);
 const person=(await call('/api/people','POST',{name:'Test Sarıçiçek',nickname:'Fıstıkçı'})).body.id;
 assert.ok((await call('/api/search?q=fistikci','GET',null,a.email)).body.items.some(p=>p.id===person));
});
test('Konak undo is author-scoped and time-limited; activity groups visible comments and marks read',async()=>{
 const {call,member,db}=fixture();const a=await member('a@test.invalid'),b=await member('b@test.invalid');
 const id=(await call('/api/experience/feed','POST',{body:'Selam aile',clientId:crypto.randomUUID()},a.email)).body.id;
 await call('/api/experience/feed/'+id+'/comments','POST',{body:'Merhaba'},b.email);
 const activity=await call('/api/experience/feed/activity','GET',null,a.email);assert.equal(activity.status,200,JSON.stringify(activity.body));assert.equal(activity.body.comments[0].count,1);
 await call('/api/experience/preferences','PUT',{markRead:true},a.email);assert.equal((await call('/api/experience/feed/activity','GET',null,a.email)).body.comments.length,0);
 await call('/api/experience/feed/'+id,'DELETE',{},a.email);assert.equal((await call('/api/experience/feed/'+id+'/restore','POST',{},b.email)).status,404);
 assert.equal((await call('/api/experience/feed/'+id+'/restore','POST',{},a.email)).status,200);
 await call('/api/experience/feed/'+id,'DELETE',{},a.email);db.prepare('UPDATE feed_posts SET deletedAt=? WHERE id=?').run('2000-01-01T00:00:00.000Z',id);
 assert.equal((await call('/api/experience/feed/'+id+'/restore','POST',{},a.email)).status,409);
});
test('Konak message search and preferences remain private; removed group members lose search access',async()=>{
 const {call,member}=fixture();const a=await member('a@test.invalid'),b=await member('b@test.invalid'),c=await member('c@test.invalid');
 await call('/api/experience/preferences','PUT',{notifications:{messages:false,tags:true},easy:true},a.email);
 assert.equal((await call('/api/experience/preferences','GET',null,a.email)).body.notifications.messages,false);
 assert.deepEqual((await call('/api/experience/preferences','GET',null,b.email)).body,{});
 await call('/api/experience/conversations/dm/'+b.id,'POST',{body:'Fıstıklı gizli selam',clientId:crypto.randomUUID()},a.email);
 const group=(await call('/api/archive/groups','POST',{name:'Test konuşma',members:[a.id,b.id]})).body.id;
 await call('/api/experience/conversations/group/'+group,'POST',{body:'Fıstıklı grup selam',clientId:crypto.randomUUID()},a.email);
 assert.equal((await call('/api/experience/message-search?q=fistikli','GET',null,b.email)).body.items.length,2);
 assert.equal((await call('/api/experience/message-search?q=fistikli','GET',null,c.email)).body.items.length,0);
 assert.equal((await call('/api/search?q=fistikli','GET',null,b.email)).body.items.length,0);
 await call('/api/archive/groups/'+group,'DELETE',{userId:b.id});assert.equal((await call('/api/experience/message-search?q=fistikli','GET',null,b.email)).body.items.length,1);
 assert.equal((await call('/api/experience/review','GET',null,b.email)).status,403);
});
test('feed privacy covers media, comments, saved posts and audience revocation',async()=>{const{call,member,files}=fixture();const a=await member('a@test.invalid'),b=await member('b@test.invalid'),c=await member('c@test.invalid');const draft={body:'Private family photograph',date:'2000-01-02',place:'Test location',description:'Test family memory',outsiders:'Test guest',kind:'memory',peopleIds:[],visibility:'selected',userIds:[b.id],image:png,clientId:crypto.randomUUID()};const made=await call('/api/experience/feed','POST',draft,a.email);assert.equal(made.status,201,JSON.stringify(made.body));const p='/api/experience/feed/'+made.body.id;assert.equal((await call('/api/experience/feed','POST',draft,a.email)).body.id,made.body.id);assert.equal(files.size,1);assert.equal((await call(p,'GET',null,c.email)).status,404);assert.equal((await call('/api/experience/feed/media/'+made.body.id,'GET',null,c.email)).status,404);assert.equal((await call('/api/experience/feed/media/'+made.body.id,'GET',null,b.email)).status,200);assert.equal((await call(p+'/comments','POST',{body:'Hello'},b.email)).status,201);assert.equal((await call(p+'/comments','GET',null,c.email)).status,404);await call(p+'/like','PUT',{},b.email);await call(p+'/like','PUT',{},b.email);assert.equal((await call(p,'GET',null,b.email)).body.likes,1);await call(p+'/save','PUT',{},b.email);assert.equal((await call('/api/experience/feed?saved=1','GET',null,b.email)).body.items.length,1);assert.equal((await call(p,'PATCH',{...draft,visibility:'private'},a.email)).status,200);assert.equal((await call(p,'GET',null,b.email)).status,404);assert.equal((await call('/api/experience/feed?saved=1','GET',null,b.email)).body.items.length,0);assert.equal((await call('/api/account','DELETE',{confirm:'HESABIMI SİL'},a.email)).status,200);});
test('feed protects guarded people, group revocation and cross-post replies',async()=>{const{call,member}=fixture();const a=await member('a@test.invalid'),b=await member('b@test.invalid');const person=(await call('/api/people','POST',{name:'Child profile'})).body.id;await call('/api/archive/guardians','PUT',{personId:person,userId:a.id});const make=async data=>await call('/api/experience/feed','POST',{body:'A family post',clientId:crypto.randomUUID(),...data},a.email);const child=await make({peopleIds:[person]});assert.equal(child.status,201);assert.equal((await call('/api/experience/feed/'+child.body.id,'GET',null,b.email)).status,404);const group=(await call('/api/archive/groups','POST',{name:'Family friends',members:[a.id,b.id]})).body.id;const x=(await make({visibility:'group',groupId:group})).body.id,y=(await make({})).body.id;await call('/api/experience/feed/'+x+'/comments','POST',{body:'First'},b.email);const comment=(await call('/api/experience/feed/'+x+'/comments','GET',null,b.email)).body.items[0];assert.equal((await call('/api/experience/feed/'+y+'/comments','POST',{body:'Wrong parent',parentId:comment.id},b.email)).status,400);assert.equal((await call('/api/experience/feed/'+y+'/pin','PUT',{pinned:true},b.email)).status,403);await call('/api/archive/groups/'+group,'DELETE',{userId:b.id});assert.equal((await call('/api/experience/feed/'+x,'GET',null,b.email)).status,404);});
test('feed pagination is stable and notifications obey current visibility',async()=>{const{call,member}=fixture();const a=await member('a@test.invalid');const person=(await call('/api/people','POST',{name:'Adult profile'})).body.id;await call('/api/experience/profile/'+person,'PUT',{userId:a.id,fields:{}});for(let i=0;i<22;i++)assert.equal((await call('/api/experience/feed','POST',{body:'Post '+i,clientId:crypto.randomUUID(),peopleIds:i===21?[person]:[]})).status,201);const first=(await call('/api/experience/feed','GET',null,a.email)).body,second=(await call('/api/experience/feed?before='+first.before,'GET',null,a.email)).body;assert.equal(first.items.length,20);assert.equal(second.items.length,2);assert.equal(new Set([...first.items,...second.items].map(x=>x.id)).size,22);assert.equal((await call('/api/experience/feed/notifications','GET',null,a.email)).body.items.length,1);await call('/api/experience/feed/notifications','POST',{},a.email);assert.equal((await call('/api/experience/feed/notifications','GET',null,a.email)).body.items.length,0);});
