import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
import {webcrypto} from 'node:crypto';
// Render-function smoke checks; not a substitute for browser visual QA.
function harness(){const app={innerHTML:''},dialog={open:false,style:{},addEventListener(){},showModal(){this.open=true;},close(){this.open=false;},querySelector(){return null;}},elements={'#app':app,'#dialog':dialog};const storage=new Map();const context={console,URLSearchParams,URL,Date,Map,Set,Math,Number,String,Array,Object,Promise,JSON,crypto:webcrypto,structuredClone,setTimeout,clearTimeout,setInterval:()=>0,clearInterval(){},location:{protocol:'https:',search:'',hash:'',pathname:'/'},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},document:{querySelector:s=>elements[s]||null,querySelectorAll:()=>[],addEventListener(){}},history:{replaceState(){}},scrollTo(){},addEventListener(){},SF_PREVIEW:true};context.window=context;const ctx=vm.createContext(context);vm.runInContext(readFileSync('public/demo.js','utf8'),ctx);vm.runInContext(readFileSync('public/community.js','utf8'),ctx);ctx.familyEnhancements.bind=()=>{};vm.runInContext(readFileSync('public/app.js','utf8'),ctx);return{ctx,app};}
test('all primary pages render without exceptions or corrupting native history',async()=>{const {ctx,app}=harness();await new Promise(r=>setTimeout(r,10));assert.match(app.innerHTML,/Evine hoş geldin/);for(const page of ['people','tree','gallery','calendar','history','places','chat','documents','profile','settings']){vm.runInContext(`route='${page}';personId='p0';render()`,ctx);assert.ok(app.innerHTML.includes('Sarıçiçek'));assert.ok(!app.innerHTML.includes('NaN'));}assert.equal(typeof ctx.history.replaceState,'function');});
test('user content is escaped before rendering',async()=>{const{ctx,app}=harness();await new Promise(r=>setTimeout(r,10));vm.runInContext(`state.people[0].name='<img src=x onerror=alert(1)>'; route='people';render()`,ctx);assert.ok(app.innerHTML.includes('&lt;img'));assert.ok(!app.innerHTML.includes('<img src=x'));});
test('member rendering omits management and person mutation controls',async()=>{const{ctx,app}=harness();await new Promise(r=>setTimeout(r,10));vm.runInContext(`state.user.role='member';route='people';render()`,ctx);assert.ok(!app.innerHTML.includes('data-action="add-person"'));assert.ok(!app.innerHTML.includes('Yönetim paneli'));});
