// Deliberately local-only. Never accepts a production URL or user credentials.
import {mkdtempSync,readFileSync,writeFileSync,rmSync} from 'node:fs';
import {tmpdir,cpus,totalmem} from 'node:os';
import {join} from 'node:path';
import {spawn,execFileSync} from 'node:child_process';
import {once} from 'node:events';
import {createHash,randomUUID} from 'node:crypto';
import {DatabaseSync} from 'node:sqlite';
import net from 'node:net';
const data=mkdtempSync(join(tmpdir(),'saricicek-stress-')),probe=net.createServer();probe.listen(0,'127.0.0.1');await once(probe,'listening');const port=probe.address().port;await new Promise(r=>probe.close(r));
const origin='http://127.0.0.1:'+port,env={...process.env,DATA_DIR:data,PORT:String(port),HOST:'127.0.0.1',APP_ORIGIN:origin},hash=s=>createHash('sha256').update(s).digest('hex'),users=[],report={date:new Date().toISOString(),fixture:{users:1000,people:5000,messages:20000,archiveEntries:5000},environment:{node:process.version,cpu:cpus()[0]?.model,logicalCPUs:cpus().length,ramGB:Math.round(totalmem()/1024**3)},bursts:[]};
let child;
try{
 execFileSync(process.execPath,['--input-type=module','-e',"await import('./src/db.mjs');"],{env,stdio:'pipe'});
 const db=new DatabaseSync(join(data,'family.sqlite'));db.exec('BEGIN');
 for(let i=0;i<1000;i++){const id='stress-user-'+i,token=randomUUID(),csrf=randomUUID();users.push({id,token,csrf});db.prepare('INSERT INTO users VALUES(?,?,?,?,?,?,?)').run(id,'Test Üye '+i,i+'@fixture.invalid','not-a-real-password-hash','member',1,report.date);db.prepare('INSERT INTO sessions VALUES(?,?,?,?)').run(hash(token),id,csrf,Date.now()+3600000);}
 for(let i=0;i<5000;i++){db.prepare('INSERT INTO people(id,name,place,createdAt,updatedAt) VALUES(?,?,?,?,?)').run('p-'+i,'Deneme Kişi '+i,'Gaziantep',report.date,report.date);db.prepare('INSERT INTO archive_entries VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,NULL)').run('entry-'+i,'story','Gaziantep hatırası '+i,'Stres testi için kurmaca arşiv metni',null,null,null,'{}','family','approved',null,users[i%1000].id,report.date,report.date);}
 for(let i=0;i<20000;i++)db.prepare('INSERT INTO messages(senderId,recipientId,clientId,body,createdAt) VALUES(?,?,?,?,?)').run(users[i%1000].id,users[(i+1)%1000].id,'seed-'+i,'Test mesajı',report.date);
 db.exec('COMMIT');db.close();
 child=spawn(process.execPath,['src/server.mjs'],{env,stdio:['ignore','pipe','pipe']});let stderr='';child.stderr.on('data',b=>stderr+=b);await Promise.race([once(child.stdout,'data'),once(child,'exit').then(()=>{throw Error('Server startup failed '+stderr);})]);
 async function request(i,round){const u=users[i%1000],peer=users[(i+1)%1000].id;const options={headers:{Cookie:'sf_session='+u.token,Origin:origin,'Content-Type':'application/json','X-CSRF-Token':u.csrf},signal:AbortSignal.timeout(30000)};let path;switch(i%5){case 0:path='/api/chat/unread';break;case 1:path='/api/search?q=Gaziantep';break;case 2:path='/api/bootstrap';break;case 3:path='/api/chat/messages/'+peer;break;default:path='/api/chat/messages/'+peer;options.method='POST';options.body=JSON.stringify({body:'Burst '+round,clientId:randomUUID()});}
 const start=performance.now();try{const r=await fetch(origin+path,options);const body=await r.json();return{ms:performance.now()-start,status:r.status,valid:r.ok&&(path.startsWith('/api/search')?body.items?.length>0:true)};}catch(e){return{ms:performance.now()-start,status:0,valid:false,error:e.name};}}
 for(const concurrency of [100,250,500,1000]){const started=performance.now(),rows=[];for(let round=0;round<2;round++)rows.push(...await Promise.all(Array.from({length:concurrency},(_,i)=>request(i,round))));const elapsed=performance.now()-started,sorted=rows.map(x=>x.ms).sort((a,b)=>a-b),percentile=p=>Math.round(sorted[Math.ceil(sorted.length*p)-1]);const result={concurrency,requests:rows.length,errors:rows.filter(x=>!x.valid).length,p50ms:percentile(.5),p95ms:percentile(.95),p99ms:percentile(.99),requestsPerSecond:Math.round(rows.length/(elapsed/1000)),elapsedMs:Math.round(elapsed),statuses:Object.fromEntries([...new Set(rows.map(x=>x.status))].map(status=>[status,rows.filter(x=>x.status===status).length]))};report.bursts.push(result);console.log(JSON.stringify(result));}
 const controllers=[],readers=[];const started=performance.now();const streams=await Promise.all(users.map(async u=>{const controller=new AbortController();controllers.push(controller);try{const r=await fetch(origin+'/api/chat/stream',{headers:{Cookie:'sf_session='+u.token},signal:controller.signal});if(!r.ok)return false;const reader=r.body.getReader();readers.push(reader);const first=await reader.read();return new TextDecoder().decode(first.value).includes('event: change');}catch{return false;}}));
 report.streams={connections:1000,opened:streams.filter(Boolean).length,initialDeliveryMs:Math.round(performance.now()-started)};for(const c of controllers)c.abort();await Promise.allSettled(readers.map(r=>r.cancel()));
 report.serverMemory=readFileSync('/proc/'+child.pid+'/status','utf8').split('\n').filter(x=>/^Vm(HWM|RSS):/.test(x)).join('; ');report.serverErrors=stderr.split('\n').filter(x=>x&&!x.includes('ExperimentalWarning')&&!x.includes('trace-warnings')).slice(-10);
 const check=new DatabaseSync(join(data,'family.sqlite'));report.integrity=check.prepare('PRAGMA integrity_check').get().integrity_check;report.foreignKeyErrors=check.prepare('PRAGMA foreign_key_check').all().length;check.close();
 writeFileSync('docs/STRESS-RESULTS.json',JSON.stringify(report,null,2)+'\n');
 writeFileSync('docs/STRESS-RESULTS.md','# Kontrollü stres testi\n\n'+report.date+'\n\n1000 ayrı oturum, 5000 kişi, 5000 arşiv kaydı ve 20000 başlangıç mesajı. Yalnızca yerel, geçici test verisi kullanıldı. Her aşama iki paralel istek dalgasıdır; sürekli 1000 aktif kullanıcı SLA testi değildir.\n\nİş yükü: %20 arama, %20 ana veri yükleme, %20 sohbet okuma, %20 sohbet yazma, %20 okunmamış sayacı.\n\n| Paralel istek | Toplam | Hata | p50 ms | p95 ms | p99 ms | İstek/sn |\n|---|---|---|---|---|---|---|\n'+report.bursts.map(r=>'| '+[r.concurrency,r.requests,r.errors,r.p50ms,r.p95ms,r.p99ms,r.requestsPerSecond].join(' | ')+' |').join('\n')+'\n\nSSE ilk bağlantı: '+report.streams.opened+'/1000; '+report.streams.initialDeliveryMs+' ms. Uzun süreli bağlantı dayanıklılığı ölçülmedi.\n\nSQLite bütünlük: '+report.integrity+'; yabancı anahtar hatası: '+report.foreignKeyErrors+'.\n\n'+report.serverMemory+'\n\nBu sonuç Node/SQLite yerel sürümüne aittir. Hosted D1/R2 ağ gecikmeleri, CDN, gerçek medya yüklemeleri, push servisleri, mobil pil/arka plan davranışı ve dağıtık gerçek kullanıcı yükü bu testin kapsamı dışındadır.\n');
 console.log(JSON.stringify({streams:report.streams,integrity:report.integrity,foreignKeyErrors:report.foreignKeyErrors,memory:report.serverMemory}));
 if(report.bursts.some(r=>r.errors)||report.streams.opened!==1000||report.integrity!=='ok'||report.foreignKeyErrors)process.exitCode=1;
}finally{if(child){child.kill();await once(child,'exit').catch(()=>{});}rmSync(data,{recursive:true,force:true});}
