// worker/assets.mjs is generated by `npm run build` (every public file as base64); this lets type
// checking run before the build.
export declare const assets: Record<string, { data: string; type: string }>;
