import {assert,clean,validDate,personInput,validateRelation} from '../src/domain.mjs';
import {community,communityPath} from '../src/community.mjs';
import {assets} from './assets.mjs';
const hex=bytes=>Array.from(new Uint8Array(bytes),v=>v.toString(16).padStart(2,'0')).join('');
const from64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
const now=()=>new Date().toISOString(),randomUUID=()=>crypto.randomUUID();
const token=()=>Array.from(crypto.getRandomValues(new Uint8Array(32)),v=>v.toString(16).padStart(2,'0')).join('');
const hash=async v=>hex(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v)));
const publicUser=u=>({id:u.id,name:u.name,email:u.email,role:u.role,active:u.active});
const staff=u=>assert(u.role==='owner'||u.role==='moderator',403,'Bu işlem için moderatör yetkisi gerekiyor.');
const owner=u=>assert(u.role==='owner',403,'Bu işlem yalnızca aile yöneticisine açık.');
const defaults={familyTitle:'Sarıçiçek',familyStory:'Bir aile, birbirine anlatılan hikâyelerle yaşar. Köklerimizi, anılarımızı ve bizi bir arada tutan bağları birlikte koruyoruz.',mailDomain:''};
function concat(chunks,length){const result=new Uint8Array(length);let offset=0;for(const c of chunks){result.set(c,offset);offset+=c.length;}return result;}
async function body(req,max=12*1024*1024){assert(Number(req.headers.get('content-length')||0)<=max,413,'Dosya veya istek çok büyük.');const reader=req.body?.getReader();let chunks=[],length=0;if(reader)while(true){const {done,value}=await reader.read();if(done)break;length+=value.length;if(length>max){await reader.cancel();assert(false,413,'Dosya veya istek çok büyük.');}chunks.push(value);}try{return JSON.parse(new TextDecoder().decode(concat(chunks,length))||'{}');}catch{assert(false,400,'İstek biçimi geçersiz.');}}
const headers={'X-Content-Type-Options':'nosniff','Referrer-Policy':'same-origin','Cache-Control':'no-store','Content-Security-Policy':"default-src 'self'; img-src 'self' data: blob:; style-src 'self' 'unsafe-inline'; script-src 'self'; connect-src 'self'; base-uri 'none'; form-action 'self'"};
function json(_res,status,data){return new Response(JSON.stringify(data),{status,headers:{...headers,'Content-Type':'application/json; charset=utf-8'}});}
function imageType(b){if([137,80,78,71,13,10,26,10].every((v,i)=>b[i]===v))return['png','image/png'];if(b[0]===255&&b[1]===216&&b[2]===255)return['jpg','image/jpeg'];if(new TextDecoder().decode(b.subarray(0,4))==='RIFF'&&new TextDecoder().decode(b.subarray(8,12))==='WEBP')return['webp','image/webp'];return null;}
export default {async fetch(req,env){
 const res=null,url=new URL(req.url),origin=url.origin,path=url.pathname,method=req.method;
 try{
 if(path==='/health')return json(res,200,{ok:true,storage:'D1/R2'});
 if(path==='/api/config')return json(res,200,{demo:false,configured:true,auth:'chatgpt'});
 if(!path.startsWith('/api/')&&!path.startsWith('/media/')&&!path.startsWith('/document/')){assert(['GET','HEAD'].includes(method),405,'Yöntem desteklenmiyor.');const asset=assets[path==='/'?'/index.html':path];assert(asset,404,'Dosya bulunamadı.');return new Response(method==='HEAD'?null:from64(asset.data),{headers:{...headers,'Content-Type':asset.type}});}
 assert(env.DB&&env.BUCKET,503,'Arşiv bağlantısı şu anda kullanılamıyor.');
 const stmt=(sql,...args)=>env.DB.prepare(sql).bind(...args),all=async(sql,...args)=>(await stmt(sql,...args).all()).results,one=(sql,...args)=>stmt(sql,...args).first(),run=(sql,...args)=>stmt(sql,...args).run();
 const batch=items=>env.DB.batch(items.map(([sql,...args])=>stmt(sql,...args)));
 const audit=(uid,action,id='')=>run('INSERT INTO audit(userId,action,entityId,createdAt) VALUES(?,?,?,?)',uid,action,id,now());
 const settings=async()=>({...defaults,...Object.fromEntries((await all('SELECT * FROM settings')).map(x=>[x.key,x.value]))});
 const decorate=async items=>{const ids=new Set(items.map(x=>x.id));const tags=(await all('SELECT * FROM photo_people')).filter(x=>ids.has(x.photoId));return items.map(p=>({...p,url:'/media/'+p.id,peopleIds:tags.filter(x=>x.photoId===p.id).map(x=>x.personId)}));};
 const limit=async(key,max=10,ms=900000)=>{const result=await stmt('INSERT INTO throttle(key,count,expires) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN expires<? THEN 1 ELSE count+1 END,expires=CASE WHEN expires<? THEN excluded.expires ELSE expires END RETURNING count',key,Date.now()+ms,Date.now(),Date.now()).first();assert(result.count<=max,429,'Çok fazla deneme. Lütfen daha sonra tekrar deneyin.');};
 const authId=req.headers.get('oai-authenticated-user-id'),email=clean(req.headers.get('oai-authenticated-user-email')).toLowerCase();
 assert(authId&&email,401,'Oturum açmanız gerekiyor.');
 assert(env.CSRF_SECRET,503,'Oturum doğrulaması yapılandırılmamış.');
 const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(env.CSRF_SECRET),{name:'HMAC',hash:'SHA-256'},false,['sign']);
 const csrf=hex(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(authId+'|'+origin)));
 if(!['GET','HEAD'].includes(method)){assert(req.headers.get('origin')===origin,403,'İstek kaynağı doğrulanamadı.');assert(req.headers.get('content-type')?.startsWith('application/json'),415,'JSON içerik gerekiyor.');assert(req.headers.get('x-csrf-token')===csrf,403,'Oturum doğrulaması başarısız. Sayfayı yenileyin.');}
 let u=await one('SELECT * FROM users WHERE authId=?',authId);
 if(!u&&email===env.OWNER_EMAIL?.toLowerCase()){
  await run("INSERT OR IGNORE INTO users(id,name,email,authId,role,active,createdAt) SELECT ?,?,?,?,'owner',1,? WHERE NOT EXISTS(SELECT 1 FROM users WHERE role='owner')",randomUUID(),'Kerem Sarıçiçek',email,authId,now());
  u=await one('SELECT * FROM users WHERE authId=?',authId);
 }
 if(path==='/api/me'&&method==='GET')return json(res,200,{user:u?.active?publicUser(u):null,csrf});
 if(path==='/api/accept-invite'&&method==='POST'){
  assert(!u,409,'Bu hesap zaten kayıtlı.');const b=await body(req,4096),name=clean(b.name,120);assert(name.length>=2,400,'Ad soyad girin.');const digest=await hash(clean(b.token,100)),id=randomUUID(),time=Date.now();
  await batch([["INSERT INTO users(id,name,email,authId,role,active,createdAt) SELECT ?,?,email,?,role,1,? FROM invites WHERE token=? AND email=? AND used=0 AND expires>?",id,name,authId,now(),digest,email,time],["UPDATE invites SET used=1 WHERE token=? AND EXISTS(SELECT 1 FROM users WHERE id=?)",digest,id]]);
  u=await one('SELECT * FROM users WHERE id=?',id);assert(u,400,'Davet geçersiz, süresi dolmuş veya başka bir e-posta adresine ait.');await audit(u.id,'Davet kabul edildi');return json(res,201,{user:publicUser(u),csrf});
 }
 assert(u&&u.active,403,'Bu hesap aileye henüz davet edilmedi veya erişimi donduruldu.');
 if(communityPath(path))return await community({path,method,url,u,read:max=>body(req,max),all,one,run,batch,storage:env.BUCKET,limit,hosted:true});
  if(path==='/api/bootstrap'&&method==='GET')return json(res,200,{
   user:publicUser(u),settings:(await settings()),people:(await all('SELECT * FROM people WHERE deletedAt IS NULL ORDER BY name')),relations:(await all('SELECT r.* FROM relations r JOIN people a ON a.id=r.personA JOIN people b ON b.id=r.personB WHERE a.deletedAt IS NULL AND b.deletedAt IS NULL')),
   photos:await decorate((await all(`SELECT id,title,date,place,description,createdBy,status,createdAt FROM photos WHERE deletedAt IS NULL AND (status='approved' OR createdBy=? OR ?!='member') ORDER BY createdAt DESC,id DESC LIMIT 200`,u.id,u.role))),
   events:(await all(`SELECT * FROM events WHERE deletedAt IS NULL AND (status='approved' OR createdBy=? OR ?!='member') ORDER BY date DESC LIMIT 1000`,u.id,u.role)),
   photoCount:(await one(`SELECT COUNT(*) n FROM photos WHERE deletedAt IS NULL AND status='approved'`)).n,
  });
  if(path==='/api/people'&&method==='POST'){staff(u);const b=personInput(await body(req,16000)),id=randomUUID(),date=now();(await run('INSERT INTO people VALUES(?,?,?,?,?,?,?,?,?,?,?,NULL)',id,b.name,b.birthDate,b.deathDate,b.place,b.country,b.biography,b.source,u.id,date,date));(await audit(u.id,'Kişi eklendi',id));return json(res,201,{id});}
  const personMatch=path.match(/^\/api\/people\/([\w-]+)$/);
  if(personMatch){staff(u);const id=personMatch[1];assert((await one('SELECT id FROM people WHERE id=? AND deletedAt IS NULL',id)),404,'Kişi bulunamadı.');if(method==='PATCH'){const b=personInput(await body(req,16000));(await run('UPDATE people SET name=?,birthDate=?,deathDate=?,place=?,country=?,biography=?,source=?,updatedAt=? WHERE id=?',b.name,b.birthDate,b.deathDate,b.place,b.country,b.biography,b.source,now(),id));(await audit(u.id,'Kişi güncellendi',id));return json(res,200,{ok:true});}if(method==='DELETE'){(await run('UPDATE people SET deletedAt=? WHERE id=?',now(),id));(await audit(u.id,'Kişi arşivden kaldırıldı',id));return json(res,200,{ok:true});}}
  if(path==='/api/relations'&&method==='POST'){staff(u);const b=await body(req,4096);assert((await one('SELECT id FROM people WHERE id=? AND deletedAt IS NULL',b.personA))&&(await one('SELECT id FROM people WHERE id=? AND deletedAt IS NULL',b.personB)),400,'Her iki kişiyi de seçin.');validateRelation((await all('SELECT * FROM relations')),b.personA,b.personB,b.type);const id=randomUUID();assert((await run(`WITH RECURSIVE descendants(id) AS (SELECT ? UNION SELECT r.personB FROM relations r JOIN descendants d ON r.personA=d.id WHERE r.type!='spouse') INSERT INTO relations SELECT ?,?,?,?,? WHERE NOT EXISTS(SELECT 1 FROM relations WHERE type=? AND ((personA=? AND personB=?) OR (?='spouse' AND personA=? AND personB=?))) AND (?='spouse' OR NOT EXISTS(SELECT 1 FROM descendants WHERE id=?))`,b.personB,id,b.personA,b.personB,b.type,validDate(b.date),b.type,b.personA,b.personB,b.type,b.personB,b.personA,b.type,b.personA)).meta.changes===1,409,'Bu bağ zaten var veya soy ağacında döngü oluşturuyor.');(await audit(u.id,'Aile bağı eklendi',id));return json(res,201,{id});}
  if(path.match(/^\/api\/relations\/[\w-]+$/)&&method==='DELETE'){staff(u);const id=path.split('/').pop();(await run('DELETE FROM relations WHERE id=?',id));(await audit(u.id,'Aile bağı kaldırıldı',id));return json(res,200,{ok:true});}
  if(path==='/api/photos'&&method==='GET'){
   const offset=Math.max(0,Math.min(100000,Number(url.searchParams.get('offset'))||0));
   const items=(await all(`SELECT id,title,date,place,description,createdBy,status,createdAt FROM photos WHERE deletedAt IS NULL AND (status='approved' OR createdBy=? OR ?!='member') ORDER BY createdAt DESC,id DESC LIMIT 101 OFFSET ?`,u.id,u.role,offset));
   return json(res,200,{items:await decorate(items.slice(0,100)),hasMore:items.length>100});
  }
  if(path==='/api/photos'&&method==='POST'){
   (await limit('upload:'+u.id,50,3600000));const b=await body(req),title=clean(b.title,160);assert(title,400,'Fotoğraf başlığı girin.');assert(typeof b.data==='string',400,'Fotoğraf seçin.');const bytes=from64(b.data.replace(/^data:image\/[\w+.-]+;base64,/,'')),type=imageType(bytes);assert(type&&bytes.length<=8*1024*1024,400,'En fazla 8 MB boyutunda JPEG, PNG veya WebP yükleyin.');const date=validDate(b.date),ids=Array.isArray(b.peopleIds)?[...new Set(b.peopleIds)].slice(0,100):[];for(const id of ids)assert((await one('SELECT id FROM people WHERE id=? AND deletedAt IS NULL',id)),400,'Etiketlenen kişi bulunamadı.');const id=randomUUID(),filename=id+'.'+type[0];await env.BUCKET.put(filename,bytes,{httpMetadata:{contentType:type[1]}});
   try{await batch([['INSERT INTO photos VALUES(?,?,?,?,?,?,?,?,?,?,NULL)',id,title,date,clean(b.place),clean(b.description,5000),filename,type[1],u.id,u.role==='member'?'pending':'approved',now()],...ids.map(p=>['INSERT INTO photo_people VALUES(?,?)',id,p])]);}catch(e){await env.BUCKET.delete(filename);throw e;}await audit(u.id,'Fotoğraf yüklendi',id);return json(res,201,{id,status:u.role==='member'?'pending':'approved'});
  }
  if(path==='/api/events'&&method==='POST'){const b=await body(req,16000),title=clean(b.title,160);assert(title,400,'Başlık girin.');assert(['gathering','birthday','marriage','memorial','funeral','migration','story'].includes(b.type),400,'Olay türünü seçin.');const date=validDate(b.date,false),personId=b.personId||null;assert(!personId||(await one('SELECT id FROM people WHERE id=? AND deletedAt IS NULL',personId)),400,'Kişi bulunamadı.');const id=randomUUID();(await run('INSERT INTO events VALUES(?,?,?,?,?,?,?,?,?,?,NULL)',id,title,b.type,date,clean(b.place),clean(b.description,5000),personId,u.id,u.role==='member'?'pending':'approved',now()));(await audit(u.id,'Aile olayı eklendi',id));return json(res,201,{id});}
  const content=path.match(/^\/api\/(photos|events)\/([\w-]+)$/);
  if(content&&method==='PATCH'){const [,table,id]=content,b=await body(req,16000),item=(await one(`SELECT * FROM ${table} WHERE id=? AND deletedAt IS NULL`,id));assert(item,404,'Kayıt bulunamadı.');assert(u.role!=='member'||item.createdBy===u.id,403,'Bu kaydı düzenleyemezsiniz.');if(b.status){staff(u);assert(['approved','rejected'].includes(b.status),400,'Durum geçersiz.');(await run(`UPDATE ${table} SET status=? WHERE id=?`,b.status,id));(await audit(u.id,'İçerik '+b.status,id));}else{const title=clean(b.title,160);assert(title,400,'Başlık girin.');(await run(`UPDATE ${table} SET title=?,description=?,place=?,date=?,status=? WHERE id=?`,title,clean(b.description,5000),clean(b.place),validDate(b.date,table==='photos'),u.role==='member'?'pending':item.status,id));(await audit(u.id,'İçerik düzenlendi',id));}return json(res,200,{ok:true});}
  if(content&&method==='DELETE'){const [,table,id]=content,item=(await one(`SELECT * FROM ${table} WHERE id=? AND deletedAt IS NULL`,id));assert(item,404,'Kayıt bulunamadı.');assert(u.role!=='member'||item.createdBy===u.id,403,'Bu kaydı kaldıramazsınız.');(await run(`UPDATE ${table} SET deletedAt=? WHERE id=?`,now(),id));(await audit(u.id,'İçerik kaldırıldı',id));return json(res,200,{ok:true});}
  if(path.startsWith('/media/')&&method==='GET'){const p=(await one('SELECT * FROM photos WHERE id=? AND deletedAt IS NULL',path.slice(7)));assert(p&&(p.status==='approved'||p.createdBy===u.id||u.role!=='member'),404,'Fotoğraf bulunamadı.');const file=await env.BUCKET.get(p.filename);assert(file,404,'Fotoğraf bulunamadı.');return new Response(file.body,{headers:{...headers,'Content-Type':p.mime,'Cache-Control':'private, no-store'}});}
  if(path==='/api/admin'&&method==='GET'){staff(u);return json(res,200,{users:u.role==='owner'?(await all('SELECT id,name,email,role,active,createdAt FROM users')):[],invites:u.role==='owner'?(await all('SELECT id,email,role,expires,used FROM invites ORDER BY expires DESC')):[],audit:(await all('SELECT a.*,u.name FROM audit a LEFT JOIN users u ON u.id=a.userId ORDER BY a.id DESC LIMIT 100')),trash:{people:(await all('SELECT id,name,deletedAt FROM people WHERE deletedAt IS NOT NULL')),photos:(await all('SELECT id,title,deletedAt FROM photos WHERE deletedAt IS NOT NULL')),events:(await all('SELECT id,title,deletedAt FROM events WHERE deletedAt IS NOT NULL'))}});}
  if(path==='/api/invites'&&method==='POST'){owner(u);const b=await body(req,4096),email=clean(b.email).toLowerCase();assert(/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email),400,'Geçerli e-posta girin.');assert(['member','moderator'].includes(b.role),400,'Rol geçersiz.');assert(!(await one('SELECT id FROM users WHERE email=?',email)),409,'Üye zaten kayıtlı.');const raw=token(),id=randomUUID();(await run('INSERT INTO invites VALUES(?,?,?,?,?,?,?)',id,email,b.role,(await hash(raw)),Date.now()+7*86400000,0,u.id));(await audit(u.id,'Davet oluşturuldu',id));return json(res,201,{url:origin+'/#invite='+raw,email});}
  if(path.match(/^\/api\/invites\/[\w-]+$/)&&method==='DELETE'){owner(u);(await run('DELETE FROM invites WHERE id=?',path.split('/').pop()));return json(res,200,{ok:true});}
  const userMatch=path.match(/^\/api\/users\/([\w-]+)$/);
  if(userMatch&&method==='PATCH'){owner(u);const id=userMatch[1],target=(await one('SELECT * FROM users WHERE id=?',id));assert(target&&target.role!=='owner',400,'Kurucu hesabı bu ekrandan değiştirilemez.');const b=await body(req,4096);assert(['member','moderator'].includes(b.role)&&[0,1].includes(b.active),400,'Rol veya durum geçersiz.');(await run('UPDATE users SET role=?,active=? WHERE id=?',b.role,b.active,id));(await audit(u.id,'Üye yetkisi değiştirildi',id));return json(res,200,{ok:true});}
  if(path==='/api/restore'&&method==='POST'){staff(u);const b=await body(req,4096);assert(['people','photos','events'].includes(b.table),400,'Kayıt türü geçersiz.');(await run(`UPDATE ${b.table} SET deletedAt=NULL WHERE id=?`,b.id));(await audit(u.id,'Kayıt geri yüklendi',b.id));return json(res,200,{ok:true});}
  if(path==='/api/settings'&&method==='PATCH'){owner(u);const b=await body(req,16000);for(const key of ['familyTitle','familyStory','mailDomain'])if(key in b){const value=clean(b[key],key==='familyStory'?10000:200);if(key==='mailDomain')assert(!value||/^(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z]{2,}$/i.test(value),400,'Alan adını https:// olmadan yazın.');(await run('INSERT OR REPLACE INTO settings VALUES(?,?)',key,value));}(await audit(u.id,'Aile ayarları güncellendi'));return json(res,200,{ok:true});}
  if(path==='/api/export'&&method==='GET'){owner(u);return json(res,200,{version:1,exportedAt:now(),settings:(await settings()),people:(await all('SELECT * FROM people')),relations:(await all('SELECT * FROM relations')),photos:(await all('SELECT * FROM photos')),photoPeople:(await all('SELECT * FROM photo_people')),events:(await all('SELECT * FROM events'))});}
  return json(res,404,{error:'İşlem bulunamadı.'});
 }catch(e){if(!e.status)console.error('Family API failure',path,e.message);return json(res,e.status||500,{error:e.status?e.message:'İşlem tamamlanamadı. Lütfen tekrar deneyin.'});}
}};
