import {assert,clean,validDate,validateRelation} from './domain.mjs';
const now=()=>new Date().toISOString(),uuid=()=>crypto.randomUUID();
export const archivePath=p=>p.startsWith('/api/archive')||p.startsWith('/archive-media/');
export const photoVisibleSQL=`(NOT EXISTS(SELECT 1 FROM photo_privacy v WHERE v.photoId=photos.id AND v.visibility='private') OR photos.createdBy=?) AND NOT EXISTS(SELECT 1 FROM photo_people pp JOIN person_guardians g ON g.personId=pp.personId WHERE pp.photoId=photos.id AND g.userId!=? AND photos.createdBy!=?)`;
export async function visiblePhoto(one,u,id){const p=await one(`SELECT * FROM photos WHERE id=? AND deletedAt IS NULL AND (status='approved' OR createdBy=? OR ?!='member') AND ${photoVisibleSQL}`,id,u.id,u.role,u.id,u.id,u.id);return p;}
const kinds=['story','recipe','question','memory','memorial','achievement','source','migration','capsule','exhibition','poll','directory','quiz'];
export async function archive({path,method,url,u,read,all,one,run,batch,storage,limit}){
 const reply=(x,status=200)=>new Response(JSON.stringify(x),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}});
 const staff=()=>assert(u.role!=='member',403,'Moderatör yetkisi gerekiyor.');
 const owner=()=>assert(u.role==='owner',403,'Aile yöneticisi yetkisi gerekiyor.');
 const stamp=async(action,id)=>run('INSERT INTO audit(userId,action,entityId,createdAt) VALUES(?,?,?,?)',u.id,action,id,now());
 async function canSee(e){if(!e||e.deletedAt)return false;if(e.visibility==='private'&&e.createdBy!==u.id)return false;if(e.status!=='approved'&&e.createdBy!==u.id&&u.role==='member')return false;if(e.photoId&&!await visiblePhoto(one,u,e.photoId))return false;if(e.personId){const g=await one('SELECT * FROM person_guardians WHERE personId=?',e.personId);if(g&&g.userId!==u.id&&e.createdBy!==u.id)return false;}return true;}
 async function entry(id,unlocked=true){const e=await one('SELECT * FROM archive_entries WHERE id=?',id);assert(await canSee(e),404,'Kayıt bulunamadı.');assert(!unlocked||!e.opensAt||e.opensAt<=now(),403,'Zaman kapsülü henüz açılmadı.');return e;}
 async function decorate(e,media){const locked=!!e.opensAt&&e.opensAt>now();return{...e,body:locked?'':e.body,data:locked?{}:JSON.parse(e.data),locked,sealed:JSON.parse(e.data).sealed===true,media:locked?[]:media||await all('SELECT id,mime FROM archive_media WHERE entryId=?',e.id)};}
 async function validate(b){assert(kinds.includes(b.kind),400,'Kayıt türü geçersiz.');const title=clean(b.title,180),body=clean(b.body,16000);assert(title.length>=2,400,'En az iki harflik bir başlık yazın.');const personId=b.personId||null,photoId=b.photoId||null,eventId=b.eventId||null;assert(!personId||await one('SELECT id FROM people WHERE id=? AND deletedAt IS NULL',personId),400,'Kişi bulunamadı.');assert(!photoId||await visiblePhoto(one,u,photoId),400,'Fotoğraf bulunamadı.');assert(!eventId||await one("SELECT id FROM events WHERE id=? AND deletedAt IS NULL AND (status='approved' OR createdBy=?)",eventId,u.id),400,'Etkinlik bulunamadı.');const visibility=b.visibility==='private'?'private':'family';const d=b.data||{},data={};
  if(b.kind==='migration'){data.year=Number(d.year);data.from=clean(d.from,150);data.to=clean(d.to,150);for(const key of ['fromLat','fromLng','toLat','toLng']){data[key]=Number(d[key]);assert(Number.isFinite(data[key])&&Math.abs(data[key])<=(key.endsWith('Lat')?85:180),400,'Harita koordinatları geçersiz.');}assert(Number.isInteger(data.year)&&data.year>=1&&data.year<=new Date().getFullYear(),400,'Göç yılı geçersiz.');}
  if(['source','question'].includes(b.kind)){data.claim=clean(d.claim,300);data.narrator=clean(d.narrator,150);data.evidence=clean(d.evidence,2000);data.confidence=['documented','oral','uncertain'].includes(d.confidence)?d.confidence:'uncertain';data.documentId=d.documentId||null;if(data.documentId)assert(await one("SELECT id FROM documents WHERE id=? AND deletedAt IS NULL AND (status='approved' OR createdBy=?)",data.documentId,u.id),400,'Belge bulunamadı.');data.verified=false;}
  if(['achievement','memory','memorial','story'].includes(b.kind))data.date=validDate(d.date);
  if(b.kind==='recipe'){data.ingredients=clean(d.ingredients,8000);data.steps=clean(d.steps,12000);data.servings=clean(d.servings,100);}
  if(b.kind==='directory'){data.city=clean(d.city,150);data.profession=clean(d.profession,150);data.help=clean(d.help,2000);assert(d.consent===true,400,'Rehberde görünme izni gerekiyor.');data.consent=true;}
  if(b.kind==='poll'){data.options=[...new Set((Array.isArray(d.options)?d.options:[]).map(x=>validDate(x,false)))].slice(0,12);assert(data.options.length>=2,400,'En az iki tarih seçeneği ekleyin.');data.place=clean(d.place,200);}
  if(b.kind==='exhibition'){data.photoIds=[...new Set(Array.isArray(d.photoIds)?d.photoIds:[])].slice(0,40);assert(data.photoIds.length>0,400,'Sergiye fotoğraf seçin.');for(const id of data.photoIds)assert(await visiblePhoto(one,u,id),400,'Sergi fotoğrafı bulunamadı.');}
  if(b.kind==='quiz'){assert(Array.isArray(d.questions)&&d.questions.length>=1&&d.questions.length<=20,400,'1–20 soru ekleyin.');data.questions=d.questions.map(q=>{const question=clean(q.question,500),options=(q.options||[]).map(x=>clean(x,200));assert(question&&options.length>=2&&options.length<=4&&Number.isInteger(q.answer)&&q.answer>=0&&q.answer<options.length,400,'Soru ve doğru cevap geçersiz.');return{question,options,answer:q.answer};});}
  let opensAt=null;if(b.kind==='capsule'){data.sealed=false;assert(typeof b.opensAt==='string'&&Number.isFinite(Date.parse(b.opensAt))&&Date.parse(b.opensAt)>Date.now(),400,'Kapsül için gelecekte bir açılış tarihi seçin.');opensAt=new Date(b.opensAt).toISOString();}
  return{kind:b.kind,title,body,personId,photoId,eventId,data:JSON.stringify(data),visibility,opensAt};
 }
 if(path==='/api/archive/entries'&&method==='GET'){const kind=url.searchParams.get('kind'),offset=Math.max(0,Number(url.searchParams.get('offset'))||0);const rows=await all('SELECT e.*,u.name author FROM archive_entries e JOIN users u ON u.id=e.createdBy WHERE e.deletedAt IS NULL AND (? IS NULL OR e.kind=?) ORDER BY e.createdAt DESC LIMIT 201 OFFSET ?',kind,kind,offset);const photos=new Set((await all(`SELECT id FROM photos WHERE deletedAt IS NULL AND (status='approved' OR createdBy=? OR ?!='member') AND ${photoVisibleSQL}`,u.id,u.role,u.id,u.id,u.id)).map(x=>x.id)),guardians=new Map((await all('SELECT * FROM person_guardians')).map(x=>[x.personId,x.userId]));const media=await all('SELECT m.id,m.mime,m.entryId FROM archive_media m JOIN archive_entries e ON e.id=m.entryId WHERE e.deletedAt IS NULL');const items=[];for(const e of rows.slice(0,200))if((e.visibility!=='private'||e.createdBy===u.id)&&(e.status==='approved'||e.createdBy===u.id||u.role!=='member')&&(!e.photoId||photos.has(e.photoId))&&(!guardians.has(e.personId)||guardians.get(e.personId)===u.id||e.createdBy===u.id)){const x=await decorate(e,media.filter(m=>m.entryId===e.id));if(x.kind==='quiz'&&x.createdBy!==u.id)x.data.questions=x.data.questions.map(({answer,...q})=>q);items.push(x);}return reply({items,hasMore:rows.length>200,nextOffset:offset+200});}
 if(path==='/api/archive/entries'&&method==='POST'){await limit('archive:'+u.id,60,3600000);const b=await validate(await read(60000)),id=uuid(),time=now();await run('INSERT INTO archive_entries VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,NULL)',id,b.kind,b.title,b.body,b.personId,b.photoId,b.eventId,b.data,b.visibility,u.role==='member'&&b.visibility!=='private'?'pending':'approved',b.opensAt,u.id,time,time);await stamp('Arşiv katkısı eklendi',id);return reply({id},201);}
 const item=path.match(/^\/api\/archive\/entries\/([\w-]+)$/);
 if(item){const e=await entry(item[1],false);if(method==='GET'){const result=await decorate(e);if(e.kind==='quiz')result.data.questions=result.data.questions.map(({answer,...q})=>q);return reply(result);}if(method==='DELETE'){assert(e.createdBy===u.id||u.role!=='member',403,'Bu kaydı kaldıramazsınız.');await run('UPDATE archive_entries SET deletedAt=?,updatedAt=? WHERE id=?',now(),now(),e.id);await stamp('Arşiv katkısı kaldırıldı',e.id);return reply({ok:true});}if(method==='PATCH'){const b=await read(60000);if(b.status){staff();assert(['approved','rejected'].includes(b.status),400,'Durum geçersiz.');await run('UPDATE archive_entries SET status=?,updatedAt=? WHERE id=?',b.status,now(),e.id);}else if(b.verify){staff();assert(e.kind==='source',400,'Yalnızca kaynak kayıtları doğrulanabilir.');const d=JSON.parse(e.data);d.verified=true;d.verifiedBy=u.id;d.verifiedAt=now();await run('UPDATE archive_entries SET data=?,updatedAt=? WHERE id=?',JSON.stringify(d),now(),e.id);}else{assert(e.createdBy===u.id||u.role!=='member',403,'Bu kaydı düzenleyemezsiniz.');assert(!e.opensAt||e.opensAt<=now(),403,'Mühürlü kapsül düzenlenemez.');assert(!['quiz','poll'].includes(e.kind)||!(await one('SELECT entryId FROM archive_votes WHERE entryId=?',e.id)),409,'Katılım başladıktan sonra seçenekler değiştirilemez.');const v=await validate({...b,kind:e.kind});await run('UPDATE archive_entries SET title=?,body=?,personId=?,photoId=?,eventId=?,data=?,visibility=?,status=?,opensAt=?,updatedAt=? WHERE id=?',v.title,v.body,v.personId,v.photoId,v.eventId,v.data,v.visibility,u.role==='member'&&v.visibility!=='private'?'pending':'approved',v.opensAt,now(),e.id);}await stamp('Arşiv katkısı güncellendi',e.id);return reply({ok:true});}}
 const comments=path.match(/^\/api\/archive\/entries\/([\w-]+)\/comments$/);
 if(comments){const e=await entry(comments[1]);if(method==='GET')return reply({items:await all("SELECT c.*,u.name author FROM archive_comments c JOIN users u ON u.id=c.createdBy WHERE entryId=? AND (status='approved' OR c.createdBy=? OR ?!='member') ORDER BY createdAt",e.id,u.id,u.role)});if(method==='POST'){await limit('comment:'+u.id,60,3600000);const b=await read(20000),body=clean(b.body,5000);assert(body,400,'Hatıranı veya cevabını yaz.');await run('INSERT INTO archive_comments VALUES(?,?,?,?,?,?)',uuid(),e.id,body,u.id,now(),u.role==='member'?'pending':'approved');return reply({ok:true},201);}}
 const comment=path.match(/^\/api\/archive\/comments\/([\w-]+)$/);if(comment&&method==='PATCH'){staff();const c=await one('SELECT * FROM archive_comments WHERE id=?',comment[1]);assert(c,404,'Cevap bulunamadı.');await entry(c.entryId);const b=await read(2000);assert(['approved','rejected'].includes(b.status),400,'Durum geçersiz.');await run('UPDATE archive_comments SET status=? WHERE id=?',b.status,c.id);return reply({ok:true});}
 const finalize=path.match(/^\/api\/archive\/entries\/([\w-]+)\/finalize$/);if(finalize&&method==='POST'){staff();const e=await entry(finalize[1]);assert(e.kind==='poll'&&!e.eventId&&e.status==='approved',409,'Bu buluşma kesinleşmiş veya onay bekliyor.');const b=await read(3000),d=JSON.parse(e.data);assert(d.options.includes(b.date),400,'Oylamadaki tarihlerden birini seçin.');const id=uuid();const result=await batch([['INSERT INTO events SELECT ?,?,?,?,?,?,?,?,?,?,NULL WHERE EXISTS(SELECT 1 FROM archive_entries WHERE id=? AND eventId IS NULL AND deletedAt IS NULL)',id,e.title,'gathering',b.date,d.place||'',e.body,e.personId,u.id,'approved',now(),e.id],['UPDATE archive_entries SET eventId=?,updatedAt=? WHERE id=? AND eventId IS NULL',id,now(),e.id]]);assert(Number(result[0].meta?.changes??result[0].changes)===1,409,'Bu buluşma zaten kesinleşmiş.');return reply({id},201);}
 const votes=path.match(/^\/api\/archive\/entries\/([\w-]+)\/vote$/);if(votes){const e=await entry(votes[1]);assert(['poll','quiz'].includes(e.kind),400,'Bu kayıt oylama değil.');const d=JSON.parse(e.data);if(method==='GET')return reply({items:await all('SELECT v.userId,v.value,u.name FROM archive_votes v JOIN users u ON u.id=v.userId WHERE entryId=?',e.id)});if(method==='POST'){const b=await read(8000);let value;if(e.kind==='poll'){assert(d.options.includes(b.value),400,'Geçerli bir tarih seçin.');value=b.value;}else{assert(!await one('SELECT * FROM archive_votes WHERE entryId=? AND userId=?',e.id,u.id),409,'Bu yarışmayı zaten tamamladın.');assert(Array.isArray(b.answers)&&b.answers.length===d.questions.length,400,'Tüm soruları cevaplayın.');value=JSON.stringify({score:d.questions.reduce((s,q,i)=>s+(q.answer===b.answers[i]?1:0),0),total:d.questions.length});}if(e.kind==='quiz'){const r=await run('INSERT INTO archive_votes VALUES(?,?,?) ON CONFLICT(entryId,userId) DO NOTHING',e.id,u.id,value);assert(Number(r.meta?.changes??r.changes)===1,409,'Bu yarışmayı zaten tamamladın.');}else await run('INSERT INTO archive_votes VALUES(?,?,?) ON CONFLICT(entryId,userId) DO UPDATE SET value=excluded.value',e.id,u.id,value);return reply({value});}}
 const seal=path.match(/^\/api\/archive\/entries\/([\w-]+)\/seal$/);if(seal&&method==='POST'){const e=await entry(seal[1],false);assert(e.kind==='capsule'&&e.createdBy===u.id,403,'Yalnızca kapsül sahibi mühürleyebilir.');const d=JSON.parse(e.data);d.sealed=true;await run('UPDATE archive_entries SET data=?,updatedAt=? WHERE id=?',JSON.stringify(d),now(),e.id);return reply({ok:true});}
 const media=path.match(/^\/api\/archive\/entries\/([\w-]+)\/media$/);if(media&&method==='POST'){const e=await entry(media[1],false);assert(e.createdBy===u.id,403,'Bu kayda dosya ekleyemezsiniz.');assert(!e.opensAt||JSON.parse(e.data).sealed!==true,403,'Mühürlü kapsüle sonradan dosya eklenemez.');const b=await read(24*1024*1024);let bytes;try{bytes=Uint8Array.from(atob(String(b.data).split(',').pop()),c=>c.charCodeAt(0));}catch{assert(false,400,'Dosya okunamadı.');}const head=new TextDecoder().decode(bytes.slice(0,12));const mime=head.startsWith('OggS')?'audio/ogg':head.startsWith('RIFF')&&head.slice(8,12)==='WAVE'?'audio/wav':head.startsWith('ID3')||(bytes[0]===255&&(bytes[1]&224)===224)?'audio/mpeg':head.slice(4,8)==='ftyp'?(b.mime==='audio/mp4'?'audio/mp4':'video/mp4'):bytes[0]===26&&bytes[1]===69&&bytes[2]===223&&bytes[3]===163?(b.mime==='video/webm'?'video/webm':'audio/webm'):null;assert(mime&&bytes.length<=16*1024*1024,400,'En fazla 16 MB MP3, WAV, OGG, M4A, MP4 veya WebM seçin.');const id=uuid(),filename='archive/'+id;await storage.put(filename,bytes,{httpMetadata:{contentType:mime}});try{await run('INSERT INTO archive_media VALUES(?,?,?,?,?,?)',id,e.id,filename,mime,u.id,now());}catch(error){await storage.delete(filename);throw error;}return reply({id},201);}
 if(path.startsWith('/archive-media/')&&method==='GET'){const m=await one('SELECT * FROM archive_media WHERE id=?',path.slice(15));assert(m,404,'Dosya bulunamadı.');await entry(m.entryId);const f=await storage.get(m.filename);assert(f,404,'Dosya bulunamadı.');return new Response(f.body,{headers:{'Content-Type':m.mime,'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}});}
 if(path==='/api/archive/groups'&&method==='GET')return reply({items:await all('SELECT g.* FROM family_groups g JOIN group_members m ON m.groupId=g.id WHERE m.userId=? ORDER BY g.createdAt DESC',u.id)});
 if(path==='/api/archive/groups'&&method==='POST'){const b=await read(20000),name=clean(b.name,120),ids=[...new Set([u.id,...(Array.isArray(b.members)?b.members:[])])].slice(0,200);assert(name.length>=2,400,'Grup adı yazın.');for(const id of ids)assert(await one('SELECT id FROM users WHERE id=? AND active=1',id),400,'Üye bulunamadı.');const id=uuid();await batch([['INSERT INTO family_groups VALUES(?,?,?,?,?)',id,name,clean(b.description,2000),u.id,now()],...ids.map(x=>['INSERT INTO group_members VALUES(?,?)',id,x])]);return reply({id},201);}
 const group=path.match(/^\/api\/archive\/groups\/([\w-]+)(?:\/(members|messages))?$/);if(group){const id=group[1],g=await one('SELECT g.* FROM family_groups g JOIN group_members m ON m.groupId=g.id WHERE g.id=? AND m.userId=?',id,u.id);assert(g,404,'Grup bulunamadı.');if(method==='GET')return reply({group:g,members:await all('SELECT u.id,u.name FROM users u JOIN group_members m ON m.userId=u.id WHERE m.groupId=?',id),items:await all('SELECT m.*,u.name FROM group_messages m JOIN users u ON u.id=m.userId WHERE groupId=? ORDER BY m.id DESC LIMIT 100',id)});if(method==='POST'&&group[2]==='messages'){await limit('groupchat:'+u.id,60,60000);const b=await read(20000),body=clean(b.body,4000);assert(body,400,'Mesaj yazın.');await run('INSERT INTO group_messages(groupId,userId,body,createdAt) VALUES(?,?,?,?)',id,u.id,body,now());return reply({ok:true},201);}if(method==='POST'&&group[2]==='members'){assert(g.createdBy===u.id,403,'Grup kurucusu üyeleri yönetir.');const b=await read(2000);assert(await one('SELECT id FROM users WHERE id=? AND active=1',b.userId),400,'Üye bulunamadı.');await run('INSERT OR IGNORE INTO group_members VALUES(?,?)',id,b.userId);return reply({ok:true});}if(method==='DELETE'){const b=await read(2000),uid=b.userId||u.id;assert(uid===u.id||g.createdBy===u.id,403,'Yetkiniz yok.');assert(uid!==g.createdBy,409,'Grup kurucusu gruptan ayrılamaz.');await run('DELETE FROM group_members WHERE groupId=? AND userId=?',id,uid);return reply({ok:true});}}
 if(path==='/api/archive/transfer'&&method==='POST'){owner();const b=await read(2000);assert(b.confirm==='YÖNETİMİ DEVRET'&&b.userId!==u.id,400,'Devir onayı gerekiyor.');assert(await one('SELECT id FROM users WHERE id=? AND active=1',b.userId),400,'Etkin üye seçin.');await batch([["UPDATE users SET role='owner' WHERE id=?",b.userId],["UPDATE users SET role='moderator' WHERE id=?",u.id],['INSERT INTO audit(userId,action,entityId,createdAt) VALUES(?,?,?,?)',u.id,'Aile yönetimi devredildi',b.userId,now()]]);return reply({ok:true});}
 if(path==='/api/archive/photo-settings'&&method==='PUT'){const b=await read(16000),p=await visiblePhoto(one,u,b.photoId);assert(p,404,'Fotoğraf bulunamadı.');assert(p.createdBy===u.id||u.role!=='member',403,'Fotoğrafı düzenleyemezsiniz.');assert(['private','family'].includes(b.visibility),400,'Görünürlük geçersiz.');const ids=[...new Set(Array.isArray(b.peopleIds)?b.peopleIds:[])].slice(0,100);for(const id of ids)assert(await one('SELECT id FROM people WHERE id=? AND deletedAt IS NULL',id),400,'Kişi bulunamadı.');await batch([['INSERT OR REPLACE INTO photo_privacy VALUES(?,?)',p.id,b.visibility],['DELETE FROM photo_people WHERE photoId=?',p.id],...ids.map(id=>['INSERT INTO photo_people VALUES(?,?)',p.id,id])]);return reply({ok:true});}
 if(path==='/api/archive/guardians'&&method==='GET'){owner();return reply({items:await all('SELECT g.*,p.name,u.name guardian FROM person_guardians g JOIN people p ON p.id=g.personId JOIN users u ON u.id=g.userId')});}
 if(path==='/api/archive/guardians'&&method==='PUT'){owner();const b=await read(2000);assert(await one('SELECT id FROM people WHERE id=? AND deletedAt IS NULL',b.personId),400,'Kişi bulunamadı.');assert(await one('SELECT id FROM users WHERE id=? AND active=1',b.userId),400,'Veli hesabı bulunamadı.');await run('INSERT OR REPLACE INTO person_guardians VALUES(?,?)',b.personId,b.userId);await stamp('Profil velisi atandı',b.personId);return reply({ok:true});}
 if(path==='/api/archive/guardians'&&method==='DELETE'){owner();const b=await read(2000);await run('DELETE FROM person_guardians WHERE personId=?',b.personId);return reply({ok:true});}
 if(path==='/api/archive/merges'&&method==='GET'){staff();return reply({items:await all('SELECT id,sourceId,targetId,createdAt,undoneAt FROM person_merges ORDER BY createdAt DESC LIMIT 100')});}
 if(path==='/api/archive/merges'&&method==='POST'){staff();const b=await read(2000);assert(b.sourceId!==b.targetId,400,'Farklı iki kayıt seçin.');const source=await one('SELECT * FROM people WHERE id=? AND deletedAt IS NULL',b.sourceId),target=await one('SELECT * FROM people WHERE id=? AND deletedAt IS NULL',b.targetId);assert(source&&target,400,'İki etkin kayıt seçin.');assert(!await one('SELECT personId FROM person_guardians WHERE personId IN (?,?)',source.id,target.id),409,'Veli korumalı profilleri birleştirmeden önce yönetici incelemesi gerekiyor.');const before=await all('SELECT * FROM relations'),mapped=before.map(r=>({...r,personA:r.personA===source.id?target.id:r.personA,personB:r.personB===source.id?target.id:r.personB})).filter(r=>r.personA!==r.personB),after=[];for(const r of mapped){if(after.some(x=>x.type===r.type&&(x.personA===r.personA&&x.personB===r.personB||r.type==='spouse'&&x.personA===r.personB&&x.personB===r.personA)))continue;validateRelation(after,r.personA,r.personB,r.type);after.push(r);}const tags=await all('SELECT * FROM photo_people WHERE personId=?',source.id),events=await all('SELECT id FROM events WHERE personId=?',source.id),entries=await all('SELECT id FROM archive_entries WHERE personId=?',source.id);const id=uuid(),date=now(),snap={before,after,source,events,entries,tags,existingTags:await all('SELECT * FROM photo_people WHERE personId=?',target.id)};await batch([['INSERT INTO person_merges VALUES(?,?,?,?,?,?,NULL)',id,source.id,target.id,JSON.stringify(snap),u.id,date],['DELETE FROM relations WHERE personA=? OR personB=?',source.id,source.id],...after.filter(r=>before.some(x=>x.id===r.id&&(x.personA===source.id||x.personB===source.id))).map(r=>['INSERT INTO relations VALUES(?,?,?,?,?)',r.id,r.personA,r.personB,r.type,r.date]),...tags.map(t=>['INSERT OR IGNORE INTO photo_people VALUES(?,?)',t.photoId,target.id]),['DELETE FROM photo_people WHERE personId=?',source.id],['UPDATE events SET personId=? WHERE personId=?',target.id,source.id],['UPDATE archive_entries SET personId=? WHERE personId=?',target.id,source.id],['UPDATE people SET deletedAt=? WHERE id=?',date,source.id]]);await stamp('Kişiler birleştirildi',id);return reply({id},201);}
 const undo=path.match(/^\/api\/archive\/merges\/([\w-]+)\/undo$/);if(undo&&method==='POST'){staff();const m=await one('SELECT * FROM person_merges WHERE id=? AND undoneAt IS NULL',undo[1]);assert(m,404,'Birleştirme bulunamadı.');const s=JSON.parse(m.snapshot),current=await all('SELECT * FROM relations');const canonical=rs=>JSON.stringify(rs.map(r=>[r.id,r.personA,r.personB,r.type,r.date]).sort((a,b)=>a[0].localeCompare(b[0])));assert(canonical(current)===canonical(s.after),409,'Aile bağları daha sonra değişti. Otomatik geri alma kapalı; yönetici incelemeli.');const extra=await one('SELECT id FROM archive_entries WHERE personId=? AND createdAt>?',m.targetId,m.createdAt);assert(!extra,409,'Birleşen profile yeni içerik eklenmiş; yönetici incelemeli.');await batch([...s.after.filter(r=>s.before.some(x=>x.id===r.id&&(x.personA===m.sourceId||x.personB===m.sourceId))).map(r=>['DELETE FROM relations WHERE id=?',r.id]),...s.before.filter(r=>r.personA===m.sourceId||r.personB===m.sourceId).map(r=>['INSERT INTO relations VALUES(?,?,?,?,?)',r.id,r.personA,r.personB,r.type,r.date]),...s.tags.map(t=>['INSERT OR IGNORE INTO photo_people VALUES(?,?)',t.photoId,m.sourceId]),...s.tags.filter(t=>!s.existingTags.some(x=>x.photoId===t.photoId)).map(t=>['DELETE FROM photo_people WHERE photoId=? AND personId=?',t.photoId,m.targetId]),...s.events.map(e=>['UPDATE events SET personId=? WHERE id=? AND personId=?',m.sourceId,e.id,m.targetId]),...s.entries.map(e=>['UPDATE archive_entries SET personId=? WHERE id=? AND personId=?',m.sourceId,e.id,m.targetId]),['UPDATE people SET deletedAt=NULL WHERE id=?',m.sourceId],['UPDATE person_merges SET undoneAt=? WHERE id=?',now(),m.id]]);await stamp('Birleştirme geri alındı',m.id);return reply({ok:true});}
 return reply({error:'Arşiv işlemi bulunamadı.'},404);
}
