import {assert} from './domain.mjs';
const tables=['content_audience','people','relations','photos','photo_people','events','documents','residences','photo_privacy','person_guardians','archive_entries','archive_comments','archive_media','archive_votes','person_merges','profile_details'];
export async function makeBackup({all,run,storage},automatic=false){const day=new Date().toISOString().slice(0,10);if(automatic){const existing=await all('SELECT id FROM archive_backups WHERE createdAt>=? LIMIT 1',day);if(existing.length)return;}const data={format:'saricicek-archive',version:3,media:[],createdAt:new Date().toISOString(),tables:{}};for(const t of tables)data.tables[t]=await all('SELECT * FROM '+t);const id=crypto.randomUUID(),filename='backups/'+id+'.json';
 const media=[...new Set(['photos','documents','archive_media'].flatMap(t=>data.tables[t].map(row=>row.filename)))];
 for(const key of media){const object=await storage.get(key);assert(object,409,'Medya dosyası eksik: tam yedek tamamlanamadı.');const bytes=new Uint8Array(await new Response(object.body).arrayBuffer());const digest=await checksum(bytes),backupKey='backups/'+id+'/media/'+key;await storage.put(backupKey,bytes);data.media.push({key,backupKey,size:bytes.byteLength,sha256:digest});}
 const bytes=new TextEncoder().encode(JSON.stringify(data));await storage.put(filename,bytes,{httpMetadata:{contentType:'application/json'}});await run('INSERT INTO archive_backups VALUES(?,?,?,?)',id,filename,data.createdAt,Object.values(data.tables).reduce((n,rs)=>n+rs.length,0));return{id};}
export async function backups({path,method,u,read,all,one,run,batch,storage}){assert(u.role==='owner',403,'Yedekler aile yöneticisine açık.');const reply=x=>new Response(JSON.stringify(x),{headers:{'Content-Type':'application/json','Cache-Control':'no-store'}});if(path==='/api/archive/backups'&&method==='GET')return reply({items:await all('SELECT id,createdAt,recordCount FROM archive_backups ORDER BY createdAt DESC LIMIT 60')});if(path==='/api/archive/backups'&&method==='POST')return reply(await makeBackup({all,run,storage}));const m=path.match(/^\/api\/archive\/backups\/([\w-]+)(?:\/(restore))?$/);assert(m,404,'Yedek bulunamadı.');const meta=await one('SELECT * FROM archive_backups WHERE id=?',m[1]);assert(meta,404,'Yedek bulunamadı.');const object=await storage.get(meta.filename);assert(object,404,'Yedek dosyası bulunamadı.');const data=JSON.parse(await new Response(object.body).text());if(method==='GET')return reply(data);assert(method==='POST'&&m[2]==='restore',405,'İşlem desteklenmiyor.');const b=await read(2000);assert(b.confirm==='ARŞİVİ GERİ YÜKLE',400,'Geri yükleme onayı gerekiyor.');// Validate every backup object before restoring anything. A missing live object is expected during recovery.
 const media=data.media||[];for(const m of media){const object=await storage.get(m.backupKey);assert(object,409,'Yedekte medya eksik; geri yükleme durduruldu.');const bytes=new Uint8Array(await new Response(object.body).arrayBuffer());assert(bytes.byteLength===m.size&&await checksum(bytes)===m.sha256,409,'Yedek dosyasının bütünlüğü doğrulanamadı.');}
 // Preserve a record snapshot even when live media is missing, then restore missing bytes only.
 const before={format:'saricicek-before-restore',createdAt:new Date().toISOString(),tables:{}};for(const t of tables)before.tables[t]=await all('SELECT * FROM '+t);await storage.put('backups/before-restore-'+crypto.randomUUID()+'.json',new TextEncoder().encode(JSON.stringify(before)));
 for(const m of media)if(!await storage.get(m.key)){const object=await storage.get(m.backupKey);await storage.put(m.key,new Uint8Array(await new Response(object.body).arrayBuffer()));}
 const statements=[];for(const t of tables){const rows=data.tables[t]??(['content_audience','profile_details'].includes(t)?[]:undefined);assert(Array.isArray(rows),400,'Yedek eksik.');for(const row of rows){const columns=Object.keys(row);assert(columns.every(k=>/^[a-zA-Z]+$/.test(k)),400,'Yedek geçersiz.');statements.push([`INSERT INTO ${t} (${columns.join(',')}) VALUES(${columns.map(()=>'?').join(',')}) ON CONFLICT DO NOTHING`,...columns.map(k=>row[k])]);}}
 // Non-destructive restore adds missing records; existing records are never overwritten.
 for(let i=0;i<statements.length;i+=80)await batch(statements.slice(i,i+80));await run('INSERT INTO audit(userId,action,entityId,createdAt) VALUES(?,?,?,?)',u.id,'Yedekteki eksik arşiv kayıtları geri eklendi',meta.id,new Date().toISOString());return reply({ok:true,mode:'missing-records-and-media'});}

async function checksum(bytes){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),b=>b.toString(16).padStart(2,'0')).join('');}
