import {publishChange} from './realtime.mjs';
import {sendPush} from './notifications.mjs';
import {hiddenPeople} from './privacy.mjs';
import {assert,clean} from './domain.mjs';
const now=()=>new Date().toISOString(),uuid=()=>crypto.randomUUID();
export const communityPath=path=>/^\/api\/(community|chat|locations|residences|attendance|documents|account)(\/|$)/.test(path)||path.startsWith('/document/');
export async function community({path,method,url,u,read,all,one,run,batch,storage,limit,hosted=false,keyText,defer}){
 const reply=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}});
 const staff=()=>assert(u.role!=='member',403,'Moderatör yetkisi gerekiyor.');
 const member=async id=>{assert(id&&id!==u.id,400,'Başka bir aile üyesi seçin.');assert(await one('SELECT id FROM users WHERE id=? AND active=1',id),404,'Üye bulunamadı.');};
 const blocked=async id=>!!await one('SELECT userId FROM blocks WHERE (userId=? AND blockedId=?) OR (userId=? AND blockedId=?)',u.id,id,id,u.id);
 const coordinates=b=>{assert(typeof b.latitude==='number'&&Number.isFinite(b.latitude)&&Math.abs(b.latitude)<=90&&typeof b.longitude==='number'&&Number.isFinite(b.longitude)&&Math.abs(b.longitude)<=180,400,'Geçerli bir konum gerekiyor.');};
 if(path==='/api/chat/unread'&&method==='GET')return reply({unread:(await one('SELECT COUNT(*) n FROM messages WHERE recipientId=? AND readAt IS NULL',u.id)).n});
 if(path==='/api/community'&&method==='GET')return reply({members:await all('SELECT id,name,role FROM users WHERE active=1 AND id!=? ORDER BY name',u.id),unread:(await one('SELECT COUNT(*) n FROM messages WHERE recipientId=? AND readAt IS NULL',u.id)).n,blocked:(await all('SELECT blockedId FROM blocks WHERE userId=?',u.id)).map(x=>x.blockedId)});
 if(path==='/api/chat/threads'&&method==='GET')return reply({items:await all(`SELECT u.id,u.name,(SELECT body FROM messages WHERE (senderId=? AND recipientId=u.id) OR (senderId=u.id AND recipientId=?) ORDER BY id DESC LIMIT 1) lastMessage,(SELECT MAX(id) FROM messages WHERE (senderId=? AND recipientId=u.id) OR (senderId=u.id AND recipientId=?)) lastId,(SELECT COUNT(*) FROM messages WHERE senderId=u.id AND recipientId=? AND readAt IS NULL) unread FROM users u WHERE active=1 AND u.id!=? ORDER BY lastId DESC,u.name`,u.id,u.id,u.id,u.id,u.id,u.id)});
 const chat=path.match(/^\/api\/chat\/messages\/([\w-]+)$/);
 if(chat){const id=chat[1];await member(id);
  if(method==='GET'){const after=Math.max(0,Number(url.searchParams.get('after'))||0),before=Math.max(0,Number(url.searchParams.get('before'))||0);let rows;if(after)rows=await all('SELECT * FROM messages WHERE ((senderId=? AND recipientId=?) OR (senderId=? AND recipientId=?)) AND id>? ORDER BY id LIMIT 100',u.id,id,id,u.id,after);else rows=(await all('SELECT * FROM messages WHERE ((senderId=? AND recipientId=?) OR (senderId=? AND recipientId=?)) AND (?=0 OR id<?) ORDER BY id DESC LIMIT 100',u.id,id,id,u.id,before,before)).reverse();return reply({items:rows,hasMore:rows.length===100,blocked:await blocked(id)});}
  if(method==='POST'){assert(!await blocked(id),403,'Bu konuşmada mesaj gönderimi kapalı.');await limit('chat:'+u.id,60,60000);const b=await read(20000),body=clean(b.body,4001),clientId=clean(b.clientId,100);assert(body.length>0&&body.length<=4000&&/^[\w-]{16,100}$/.test(clientId),400,'Mesaj en fazla 4.000 karakter olabilir.');const insert=await run('INSERT OR IGNORE INTO messages(senderId,recipientId,clientId,body,createdAt) VALUES(?,?,?,?,?)',u.id,id,clientId,body,now());const item=await one('SELECT * FROM messages WHERE senderId=? AND clientId=?',u.id,clientId);assert(item.recipientId===id,409,'Mesaj kimliği başka bir konuşmada kullanılmış.');if(Number(insert.meta?.changes??insert.changes)===1){publishChange(u.id);publishChange(id);const task=sendPush({userId:id,one,all,run,keyText,origin:url.origin});if(defer)defer(task);else await task;}return reply({item},201);}
 }
 if(path==='/api/chat/read'&&method==='POST'){const b=await read(2000);await member(b.userId);assert(Number.isSafeInteger(b.through)&&b.through>=0,400,'Mesaj sınırı geçersiz.');await run('UPDATE messages SET readAt=? WHERE senderId=? AND recipientId=? AND id<=? AND readAt IS NULL',now(),b.userId,u.id,b.through);publishChange(b.userId);return reply({ok:true});}
 if(path==='/api/chat/block'&&['POST','DELETE'].includes(method)){const b=await read(2000);await member(b.userId);if(method==='POST')await run('INSERT OR IGNORE INTO blocks VALUES(?,?)',u.id,b.userId);else await run('DELETE FROM blocks WHERE userId=? AND blockedId=?',u.id,b.userId);return reply({ok:true});}
 if(path==='/api/chat/report'&&method==='POST'){await limit('report:'+u.id,10,3600000);const b=await read(4000),m=await one('SELECT id FROM messages WHERE id=? AND recipientId=?',b.messageId,u.id);assert(m,404,'Mesaj bulunamadı.');const reason=clean(b.reason,1000);assert(reason.length>=3,400,'Şikâyet nedenini yazın.');await run('INSERT INTO reports VALUES(?,?,?,?,?,0)',uuid(),m.id,u.id,reason,now());return reply({ok:true},201);}
 if(path==='/api/chat/reports'&&method==='GET'){staff();return reply({items:await all('SELECT r.*,m.body,u.name senderName FROM reports r JOIN messages m ON m.id=r.messageId JOIN users u ON u.id=m.senderId WHERE r.resolved=0 ORDER BY r.createdAt DESC LIMIT 100')});}
 if(path==='/api/chat/reports'&&method==='PATCH'){staff();const b=await read(2000);await run('UPDATE reports SET resolved=1 WHERE id=?',b.id);return reply({ok:true});}
 if(path==='/api/locations'&&method==='GET'){
  await run('DELETE FROM location_shares WHERE expires<=?',Date.now());
  const mine=await one('SELECT precision,expires,updatedAt FROM location_shares WHERE userId=? AND expires>?',u.id,Date.now());
  const live=await all(`SELECT l.userId,u.name,l.latitude,l.longitude,l.accuracy,l.precision,l.updatedAt,l.expires FROM location_shares l JOIN users u ON u.id=l.userId WHERE u.active=1 AND l.expires>? AND l.latitude IS NOT NULL AND NOT EXISTS(SELECT 1 FROM blocks b WHERE (b.userId=? AND b.blockedId=l.userId) OR (b.userId=l.userId AND b.blockedId=?))`,Date.now(),u.id,u.id);
  const hidden=await hiddenPeople(all,u);
  return reply({mine,live:live.map(x=>({...x,latitude:Number(x.latitude),longitude:Number(x.longitude)})),residences:(await all('SELECT r.*,p.name FROM residences r JOIN people p ON p.id=r.personId WHERE p.deletedAt IS NULL AND p.deathDate IS NULL')).filter(x=>!hidden.has(x.personId)).map(x=>({...x,latitude:Number(x.latitude),longitude:Number(x.longitude)}))});
 }
 if(path==='/api/locations/consent'&&method==='POST'){const b=await read(2000);assert(b.consent===true&&['approximate','precise'].includes(b.precision)&&[1,8,24].includes(b.hours),400,'Paylaşım izni, hassasiyet ve süre seçin.');const expires=Date.now()+b.hours*3600000,shareToken=uuid();await run('INSERT OR REPLACE INTO location_shares(userId,precision,consentedAt,expires,shareToken) VALUES(?,?,?,?,?)',u.id,b.precision,now(),expires,shareToken);return reply({expires,shareToken});}
 if(path==='/api/locations'&&method==='PUT'){const b=await read(3000);coordinates(b);const share=await one('SELECT * FROM location_shares WHERE userId=? AND expires>? AND shareToken=?',u.id,Date.now(),b.shareToken);assert(share,403,'Konum paylaşımı kapalı veya süresi dolmuş.');assert(typeof b.timestamp==='number'&&Math.abs(Date.now()-b.timestamp)<300000,400,'Konum güncel değil.');await limit('location:'+u.id,30,60000);const round=n=>share.precision==='approximate'?Math.round(n*50)/50:n;const accuracy=share.precision==='approximate'?Math.max(2200,Math.round(Number(b.accuracy)||0)):Math.max(0,Math.min(100000,Math.round(Number(b.accuracy)||0)));await run('UPDATE location_shares SET latitude=?,longitude=?,accuracy=?,updatedAt=? WHERE userId=? AND expires>? AND shareToken=?',String(round(b.latitude)),String(round(b.longitude)),accuracy,now(),u.id,Date.now(),b.shareToken);return reply({ok:true});}
 if(path==='/api/locations'&&method==='DELETE'){await run('DELETE FROM location_shares WHERE userId=?',u.id);return reply({ok:true});}
 if(path==='/api/residences'&&method==='PUT'){staff();const b=await read(3000);coordinates(b);assert(!(await hiddenPeople(all,u)).has(b.personId),404,'Kişi bulunamadı.');assert(await one('SELECT id FROM people WHERE id=? AND deletedAt IS NULL',b.personId),404,'Kişi bulunamadı.');await run('INSERT OR REPLACE INTO residences VALUES(?,?,?,?,?)',b.personId,String(b.latitude),String(b.longitude),clean(b.label,200),now());return reply({ok:true});}
 if(path==='/api/residences'&&method==='DELETE'){staff();const b=await read(2000);assert(!(await hiddenPeople(all,u)).has(b.personId),404,'Kişi bulunamadı.');await run('DELETE FROM residences WHERE personId=?',b.personId);return reply({ok:true});}
 if(path==='/api/attendance'&&method==='GET'){const id=url.searchParams.get('eventId');assert(await one("SELECT id FROM events WHERE id=? AND deletedAt IS NULL AND status='approved'",id),404,'Etkinlik bulunamadı.');return reply({items:await all('SELECT a.*,u.name FROM attendance a JOIN users u ON u.id=a.userId WHERE eventId=?',id)});}
 if(path==='/api/attendance'&&method==='POST'){const b=await read(2000);assert(['yes','maybe','no'].includes(b.response),400,'Katılım tercihinizi seçin.');assert(await one("SELECT id FROM events WHERE id=? AND deletedAt IS NULL AND status='approved'",b.eventId),404,'Etkinlik bulunamadı.');await run('INSERT OR REPLACE INTO attendance VALUES(?,?,?)',b.eventId,u.id,b.response);return reply({ok:true});}
 if(path==='/api/documents'&&method==='GET')return reply({items:await all("SELECT id,title,description,createdBy,createdAt,status FROM documents WHERE deletedAt IS NULL AND (status='approved' OR createdBy=? OR ?!='member') ORDER BY createdAt DESC LIMIT 200",u.id,u.role)});
 if(path==='/api/documents'&&method==='POST'){await limit('document:'+u.id,20,3600000);const b=await read(12*1024*1024),title=clean(b.title,160);assert(title&&typeof b.data==='string',400,'Başlık ve PDF belgesi gerekiyor.');let bytes;try{bytes=Uint8Array.from(atob(b.data.replace(/^data:application\/pdf;base64,/,'')),c=>c.charCodeAt(0));}catch{assert(false,400,'PDF okunamadı.');}assert(bytes.length<=8*1024*1024&&new TextDecoder().decode(bytes.slice(0,5))==='%PDF-',400,'En fazla 8 MB bir PDF seçin.');const id=uuid(),filename='documents/'+id+'.pdf';await storage.put(filename,bytes,{httpMetadata:{contentType:'application/pdf'}});try{await run('INSERT INTO documents VALUES(?,?,?,?,?,?,?,NULL)',id,title,clean(b.description,5000),filename,u.id,now(),u.role==='member'?'pending':'approved');}catch(e){await storage.delete(filename);throw e;}return reply({id},201);}
 const doc=path.match(/^\/api\/documents\/([\w-]+)$/);
 if(doc&&['PATCH','DELETE'].includes(method)){const item=await one('SELECT * FROM documents WHERE id=? AND deletedAt IS NULL',doc[1]);assert(item,404,'Belge bulunamadı.');if(method==='PATCH'){staff();const b=await read(2000);assert(['approved','rejected'].includes(b.status),400,'Durum geçersiz.');await run('UPDATE documents SET status=? WHERE id=?',b.status,item.id);}else{assert(u.role!=='member'||item.createdBy===u.id,403,'Bu belgeyi kaldıramazsınız.');await run('UPDATE documents SET deletedAt=? WHERE id=?',now(),item.id);}return reply({ok:true});}
 if(path.startsWith('/document/')&&method==='GET'){const item=await one('SELECT * FROM documents WHERE id=? AND deletedAt IS NULL',path.slice(10));assert(item&&(item.status==='approved'||item.createdBy===u.id||u.role!=='member'),404,'Belge bulunamadı.');const file=await storage.get(item.filename);assert(file,404,'Belge bulunamadı.');return new Response(file.body,{headers:{'Content-Type':'application/pdf','Content-Disposition':'attachment; filename="aile-belgesi.pdf"','Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff','Content-Security-Policy':"sandbox; default-src 'none'"}});}
 if(path==='/api/account'&&method==='DELETE'){const b=await read(2000);assert(b.confirm==='HESABIMI SİL',400,'Silme onayını yazın.');assert(u.role!=='owner',409,'Aile yöneticisi hesabının silinmesi için önce yönetim devri gerekir.');const id=uuid();await batch([['DELETE FROM location_shares WHERE userId=?',u.id],['DELETE FROM reports WHERE reporterId=? OR messageId IN (SELECT id FROM messages WHERE senderId=? OR recipientId=?)',u.id,u.id,u.id],['DELETE FROM messages WHERE senderId=? OR recipientId=?',u.id,u.id],['DELETE FROM blocks WHERE userId=? OR blockedId=?',u.id,u.id],['DELETE FROM attendance WHERE userId=?',u.id],['DELETE FROM security_sessions WHERE userId=?',u.id],['DELETE FROM security_factors WHERE userId=?',u.id],['DELETE FROM security_recovery WHERE userId=?',u.id],['DELETE FROM push_subscriptions WHERE userId=?',u.id],['DELETE FROM group_members WHERE userId=?',u.id],["UPDATE archive_entries SET deletedAt=? WHERE createdBy=? AND (visibility='private' OR kind='directory')",now(),u.id],[`UPDATE users SET active=0,name='Silinen üye',email=?${hosted?',authId=?':''} WHERE id=?`,...(hosted?[id+'@deleted.invalid','deleted-'+id,u.id]:[id+'@deleted.invalid',u.id])]]);return reply({ok:true});}
 return reply({error:'İşlem bulunamadı.'},404);
}
