import {feed} from './feed.mjs';
import {assert,clean} from './domain.mjs';
import {hiddenPeople} from './privacy.mjs';
import {visiblePhoto} from './archive.mjs';
import {audienceAllows} from './audience.mjs';
import {publishChange} from './realtime.mjs';
import {sendPush} from './notifications.mjs';
const now=()=>new Date().toISOString();
export async function experience(ctx){
 if(ctx.path.startsWith('/api/experience/feed'))return feed(ctx);
 const {path,method,url,u,read,one,all,run,batch,storage,limit,keyText,defer}=ctx;
 const reply=(x,status=200)=>new Response(JSON.stringify(x),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store'}});
 async function thread(kind,id){assert(['dm','group'].includes(kind),400,'Konuşma türü geçersiz.');if(kind==='dm'){assert(id!==u.id&&await one('SELECT id FROM users WHERE id=? AND active=1',id),404,'Kişi bulunamadı.');return{blocked:!!await one('SELECT 1 FROM blocks WHERE (userId=? AND blockedId=?) OR (userId=? AND blockedId=?)',u.id,id,id,u.id)};}assert(await one('SELECT 1 FROM group_members WHERE groupId=? AND userId=?',id,u.id),404,'Grup bulunamadı.');return{blocked:false};}
 const where=(kind)=>kind==='dm'?'((senderId=? AND recipientId=?) OR (senderId=? AND recipientId=?))':'groupId=?';
 const params=(kind,id)=>kind==='dm'?[u.id,id,id,u.id]:[id];
 async function message(kind,id,n){return one(`SELECT * FROM ${kind==='dm'?'messages':'group_messages'} WHERE ${where(kind)} AND id=?`,...params(kind,id),n);}
 const p=path.match(/^\/api\/experience\/profile\/([\w-]+)$/);
 if(p){const id=p[1];assert(!(await hiddenPeople(all,u)).has(id)&&await one('SELECT id FROM people WHERE id=? AND deletedAt IS NULL',id),404,'Kişi bulunamadı.');const row=await one('SELECT * FROM profile_details WHERE personId=?',id),guardian=await one('SELECT userId FROM person_guardians WHERE personId=?',id),edit=u.role==='owner'||row?.userId===u.id||guardian?.userId===u.id;
 if(method==='GET'){const raw=JSON.parse(row?.fields||'{}'),fields={};for(const [k,v]of Object.entries(raw)){if(edit||v.visibility==='family'||v.visibility==='selected'&&v.users?.includes(u.id))fields[k]=edit?v:{value:v.value,visibility:v.visibility};}if(fields.cover?.value&&!await visiblePhoto(one,u,fields.cover.value))delete fields.cover;return reply({fields,canEdit:edit,userId:row?.userId||null});}
 if(method==='PUT'){assert(edit,403,'Bu profili düzenleme yetkin yok.');const b=await read(20000),fields={};for(const k of ['intro','profession','interests','cover']){const v=b.fields?.[k]||{},value=clean(v.value,k==='intro'?4000:500),visibility=['family','private','selected'].includes(v.visibility)?v.visibility:'private',users=[...new Set(Array.isArray(v.users)?v.users:[])].slice(0,200);for(const uid of users)assert(await one('SELECT id FROM users WHERE id=? AND active=1',uid),400,'Üye seçimi geçersiz.');fields[k]={value,visibility,users};}if(fields.cover.value)assert(await visiblePhoto(one,u,fields.cover.value),400,'Kapak fotoğrafına erişilemiyor.');let userId=row?.userId||null;if(u.role==='owner'&&Object.hasOwn(b,'userId')){userId=b.userId||null;if(userId){assert(await one('SELECT id FROM users WHERE id=? AND active=1',userId),400,'Hesap bulunamadı.');assert(!await one('SELECT personId FROM profile_details WHERE userId=? AND personId!=?',userId,id),409,'Bu hesap başka bir profile bağlı.');}}await run('INSERT INTO profile_details VALUES(?,?,?) ON CONFLICT(personId) DO UPDATE SET userId=excluded.userId,fields=excluded.fields',id,userId,JSON.stringify(fields));return reply({ok:true});}}
 if(path==='/api/experience/me'&&method==='GET')return reply({personId:(await one('SELECT personId FROM profile_details WHERE userId=?',u.id))?.personId||null});
 const aud=path.match(/^\/api\/experience\/audience\/(photo|archive)\/([\w-]+)$/);
 if(aud){const [_,kind,id]=aud,p=kind==='photo'?await visiblePhoto(one,u,id):await one('SELECT * FROM archive_entries WHERE id=? AND deletedAt IS NULL',id);assert(p&&p.createdBy===u.id,403,'Görünürlüğü yalnızca paylaşımın sahibi değiştirebilir.');if(method==='GET')return reply(await one('SELECT * FROM content_audience WHERE kind=? AND recordId=?',kind,id)||{mode:'family',userIds:'[]'});if(method==='PUT'){const b=await read(20000),mode=b.mode,ids=[...new Set(Array.isArray(b.userIds)?b.userIds:[])].slice(0,200);assert(['family','private','selected','group'].includes(mode),400,'Görünürlük seçin.');for(const uid of ids)assert(await one('SELECT id FROM users WHERE id=? AND active=1',uid),400,'Üye bulunamadı.');if(mode==='selected')assert(ids.length,400,'En az bir kişi seçin.');if(mode==='group')assert(await one('SELECT 1 FROM group_members WHERE groupId=? AND userId=?',b.groupId,u.id),400,'Üyesi olduğun grubu seç.');const ops=[['INSERT INTO content_audience VALUES(?,?,?,?,?) ON CONFLICT(kind,recordId) DO UPDATE SET mode=excluded.mode,userIds=excluded.userIds,groupId=excluded.groupId',kind,id,mode,JSON.stringify(ids),mode==='group'?b.groupId:null]];if(kind==='photo')ops.push(['INSERT INTO photo_privacy VALUES(?,?) ON CONFLICT(photoId) DO UPDATE SET visibility=excluded.visibility',id,mode==='private'?'private':'family']);else ops.push(['UPDATE archive_entries SET visibility=?,status=? WHERE id=?',mode==='private'?'private':'family',u.role==='member'&&p.visibility==='private'&&mode!=='private'?'pending':p.status,id]);await batch(ops);return reply({ok:true});}}
 if(path==='/api/experience/attachments'&&method==='POST'){await limit('chat-upload:'+u.id,30,3600000);const b=await read(12*1024*1024);const t=await thread(b.kind,b.targetId);assert(!t.blocked,403,'Bu konuşma engellenmiş.');let bytes;try{bytes=Uint8Array.from(atob(String(b.data).split(',').pop()),c=>c.charCodeAt(0));}catch{assert(false,400,'Dosya okunamadı.');}const h=new TextDecoder().decode(bytes.slice(0,12));const mime=bytes[0]===255&&bytes[1]===216?'image/jpeg':bytes[0]===137&&h.slice(1,4)==='PNG'?'image/png':h.startsWith('RIFF')&&h.slice(8,12)==='WEBP'?'image/webp':h.startsWith('OggS')?'audio/ogg':h.startsWith('RIFF')&&h.slice(8,12)==='WAVE'?'audio/wav':h.startsWith('ID3')?'audio/mpeg':h.slice(4,8)==='ftyp'&&b.mime?.startsWith('audio/mp4')?'audio/mp4':bytes[0]===26&&bytes[1]===69&&b.mime?.startsWith('audio/webm')?'audio/webm':null;assert(mime&&bytes.length>12&&bytes.length<=8*1024*1024,400,'8 MB’tan küçük fotoğraf veya ses dosyası seç.');const id=crypto.randomUUID(),filename='chat/'+id;await storage.put(filename,bytes,{httpMetadata:{contentType:mime}});try{await run('INSERT INTO chat_attachments VALUES(?,?,?,?,?,?,?)',id,u.id,b.kind,b.targetId,filename,mime,now());}catch(e){await storage.delete(filename);throw e;}return reply({id,mime},201);}
 const media=path.match(/^\/api\/experience\/media\/([\w-]+)$/);
 if(media&&method==='GET'){const a=await one('SELECT * FROM chat_attachments WHERE id=?',media[1]);assert(a,404,'Dosya bulunamadı.');if(a.kind==='dm')assert(a.senderId===u.id||a.targetId===u.id,404,'Dosya bulunamadı.');else await thread('group',a.targetId);const f=await storage.get(a.filename);assert(f,404,'Dosya bulunamadı.');return new Response(f.body,{headers:{'Content-Type':a.mime,'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'none'; sandbox"}});}
 const chat=path.match(/^\/api\/experience\/conversations\/(dm|group)\/([\w-]+)$/);
 if(chat){const kind=chat[1],id=chat[2],t=await thread(kind,id),table=kind==='dm'?'messages':'group_messages';
 if(method==='GET'){const before=Math.max(0,Number(url.searchParams.get('before'))||0);const clause=kind==='dm'?'((m.senderId=? AND m.recipientId=?) OR (m.senderId=? AND m.recipientId=?))':'m.groupId=?',replyScope=kind==='dm'?'((r.senderId=m.senderId AND r.recipientId=m.recipientId) OR (r.senderId=m.recipientId AND r.recipientId=m.senderId))':'r.groupId=m.groupId';const rows=(await all(`SELECT m.*,a.id attachmentId,a.mime attachmentMime,r.id replyId,r.body replyBody FROM ${table} m LEFT JOIN message_extras x ON x.kind=? AND x.messageId=m.id LEFT JOIN chat_attachments a ON a.id=x.attachmentId LEFT JOIN ${table} r ON r.id=x.replyId AND ${replyScope} WHERE ${clause} AND (?=0 OR m.id<?) ORDER BY m.id DESC LIMIT 60`,kind,...params(kind,id),before,before)).reverse(),items=rows.map(({attachmentId,attachmentMime,replyId,replyBody,...row})=>({...row,senderId:row.senderId||row.userId,attachment:attachmentId?{id:attachmentId,mime:attachmentMime}:null,reply:replyId?{id:replyId,body:replyBody}:null}));const typing=kind==='dm'?await all("SELECT u.name FROM chat_typing t JOIN users u ON u.id=t.userId WHERE t.kind='dm' AND t.userId=? AND t.targetId=? AND expires>?",id,u.id,Date.now()):await all("SELECT u.name FROM chat_typing t JOIN users u ON u.id=t.userId JOIN group_members gm ON gm.userId=t.userId AND gm.groupId=t.targetId WHERE t.kind='group' AND t.targetId=? AND t.userId!=? AND expires>?",id,u.id,Date.now());return reply({items,hasMore:rows.length===60,blocked:t.blocked,typing:t.blocked?[]:typing});}
 if(method==='POST'){assert(!t.blocked,403,'Bu konuşmada gönderim kapalı.');await limit('chat:'+u.id,60,60000);const b=await read(20000),body=clean(b.body,4000),clientId=clean(b.clientId,100);assert(/^[\w-]{16,100}$/.test(clientId)&&(body||b.attachmentId),400,'Mesaj yaz veya dosya ekle.');const retry=await one('SELECT * FROM message_extras WHERE senderId=? AND clientId=?',u.id,clientId);if(retry){assert(retry.kind===kind&&await message(kind,id,retry.messageId),409,'Mesaj kimliği başka bir konuşmada kullanılmış.');return reply({ok:true});}if(b.replyId)assert(Number.isSafeInteger(b.replyId)&&b.replyId>0&&await message(kind,id,b.replyId),400,'Yanıtlanan mesaj bu konuşmada değil.');if(b.attachmentId){const a=await one('SELECT * FROM chat_attachments WHERE id=?',b.attachmentId);assert(a&&a.senderId===u.id&&a.kind===kind&&a.targetId===id,400,'Dosya bu konuşmaya ait değil.');}const text=body||(b.attachmentId?'Dosya':''),time=now();await batch([kind==='dm'?['INSERT INTO messages(senderId,recipientId,clientId,body,createdAt) VALUES(?,?,?,?,?)',u.id,id,clientId,text,time]:['INSERT INTO group_messages(groupId,userId,body,createdAt) VALUES(?,?,?,?)',id,u.id,text,time],['INSERT INTO message_extras(kind,messageId,replyId,attachmentId,clientId,senderId) VALUES(?,last_insert_rowid(),?,?,?,?)',kind,b.replyId||null,b.attachmentId||null,clientId,u.id],['DELETE FROM chat_typing WHERE userId=? AND kind=? AND targetId=?',u.id,kind,id]]);const ids=kind==='dm'?[u.id,id]:(await all('SELECT userId FROM group_members WHERE groupId=?',id)).map(x=>x.userId);ids.forEach(publishChange);if(kind==='dm'&&keyText){const task=sendPush({userId:id,one,all,run,keyText,origin:url.origin});if(defer)defer(task);else await task;}return reply({ok:true},201);}}
 const typing=path.match(/^\/api\/experience\/typing\/(dm|group)\/([\w-]+)$/);if(typing&&method==='POST'){const t=await thread(typing[1],typing[2]);assert(!t.blocked,403,'Konuşma kapalı.');await limit('typing:'+u.id,40,60000);await run('INSERT INTO chat_typing VALUES(?,?,?,?) ON CONFLICT(userId,kind,targetId) DO UPDATE SET expires=excluded.expires',u.id,typing[1],typing[2],Date.now()+6000);return reply({ok:true});}
 return reply({error:'İşlem bulunamadı.'},404);
}
