import {assert,clean,validDate} from './domain.mjs';
import {photoVisibleSQL,visiblePhoto} from './archive.mjs';
import {hiddenPeople} from './privacy.mjs';
const now=()=>new Date().toISOString();
export async function feed({path,method,url,u,read,all,one,run,batch,storage,limit}){
 const reply=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store'}});
 const params=[u.id,u.role,u.id,u.id,u.id];
 const access=`p.deletedAt IS NULL AND (p.createdBy=v.uid OR p.visibility='family' OR (p.visibility='selected' AND EXISTS(SELECT 1 FROM json_each(p.userIds) WHERE value=v.uid)) OR (p.visibility='group' AND EXISTS(SELECT 1 FROM group_members WHERE groupId=p.groupId AND userId=v.uid)))
 AND (v.role='owner' OR NOT EXISTS(SELECT 1 FROM json_each(p.peopleIds) j JOIN person_guardians g ON g.personId=j.value WHERE g.userId!=v.uid))
 AND (v.role='owner' OR NOT EXISTS(SELECT 1 FROM profile_details d JOIN person_guardians g ON g.personId=d.personId WHERE d.userId=p.createdBy AND g.userId!=v.uid))
 AND (p.photoId IS NULL OR EXISTS(SELECT 1 FROM photos WHERE id=p.photoId AND deletedAt IS NULL AND (status='approved' OR createdBy=v.uid OR v.role!='member') AND ${photoVisibleSQL}))
 AND (p.eventId IS NULL OR EXISTS(SELECT 1 FROM events e WHERE e.id=p.eventId AND e.deletedAt IS NULL AND (e.status='approved' OR e.createdBy=v.uid OR v.role!='member') AND (v.role='owner' OR NOT EXISTS(SELECT 1 FROM person_guardians g WHERE g.personId=e.personId AND g.userId!=v.uid))))`;
 const base=`WITH v AS(SELECT ? uid,? role) SELECT p.*,u.name author,(SELECT personId FROM profile_details WHERE userId=p.createdBy LIMIT 1) authorPersonId,(SELECT COUNT(*) FROM feed_reactions WHERE postId=p.id) likes,(SELECT COUNT(*) FROM feed_comments WHERE postId=p.id AND deletedAt IS NULL) comments,EXISTS(SELECT 1 FROM feed_reactions WHERE postId=p.id AND userId=v.uid) liked,EXISTS(SELECT 1 FROM feed_saved WHERE postId=p.id AND userId=v.uid) saved FROM feed_posts p JOIN users u ON u.id=p.createdBy CROSS JOIN v WHERE ${access}`;
 function decorate(p){const {filename,mime,userIds,...rest}=p;return{...rest,peopleIds:JSON.parse(p.peopleIds),...(p.createdBy===u.id?{userIds:JSON.parse(userIds)}:{}),image:filename?'/api/experience/feed/media/'+p.id:p.photoId?'/media/'+p.photoId:null};}
 async function get(id){const p=await one(base+' AND p.id=?',...params,id);assert(p,404,'Paylaşım bulunamadı veya erişimin yok.');return p;}
 async function validate(b){const kind=['post','memory','question','event'].includes(b.kind)?b.kind:'post',body=clean(b.body,6001);assert(body.length<=6000,400,'Paylaşım en fazla 6.000 karakter olabilir.');const peopleIds=[...new Set(Array.isArray(b.peopleIds)?b.peopleIds:[])].slice(0,20),hidden=await hiddenPeople(all,u);for(const id of peopleIds)assert(!hidden.has(id)&&await one('SELECT id FROM people WHERE id=? AND deletedAt IS NULL',id),400,'Etiketlenecek kişi bulunamadı.');const visibility=['family','private','selected','group'].includes(b.visibility)?b.visibility:'family',userIds=[...new Set(Array.isArray(b.userIds)?b.userIds:[])].slice(0,200);if(visibility==='selected'){assert(userIds.length,400,'En az bir kişi seç.');for(const id of userIds)assert(await one('SELECT id FROM users WHERE id=? AND active=1',id),400,'Üye bulunamadı.');}if(visibility==='group')assert(await one('SELECT groupId FROM group_members WHERE groupId=? AND userId=?',b.groupId,u.id),400,'Üyesi olduğun bir grup seç.');const photoId=b.photoId||null,eventId=b.eventId||null;if(photoId)assert(await visiblePhoto(one,u,photoId),400,'Fotoğraf bulunamadı.');if(eventId){const e=await one("SELECT * FROM events WHERE id=? AND deletedAt IS NULL AND (status='approved' OR createdBy=?)",eventId,u.id);assert(e&&!hidden.has(e.personId),400,'Etkinlik bulunamadı.');}if(kind==='event')assert(eventId,400,'Bir etkinlik seç.');return{kind,body,date:kind==='memory'?validDate(b.date):null,place:clean(b.place,200),peopleIds:JSON.stringify(peopleIds),photoId,eventId,visibility,userIds:JSON.stringify(userIds),groupId:visibility==='group'?b.groupId:null};}
 async function mentions(id,p){const ids=JSON.parse(p.peopleIds);if(!ids.length)return;const rows=await all(`SELECT DISTINCT userId FROM profile_details WHERE personId IN(${ids.map(()=>'?').join(',')}) AND userId IS NOT NULL AND userId!=?`,...ids,u.id);if(rows.length)await batch(rows.map(x=>['INSERT OR IGNORE INTO feed_notifications(postId,userId) VALUES(?,?)',id,x.userId]));}
 if(path==='/api/experience/feed'&&method==='GET'){const before=Math.max(0,Number(url.searchParams.get('before'))||0),author=url.searchParams.get('author'),person=url.searchParams.get('person'),kind=url.searchParams.get('kind'),saved=url.searchParams.get('saved')==='1';const extra=[],args=[];if(before){extra.push('p.id<?');args.push(before);}if(author){extra.push('p.createdBy=?');args.push(author);}if(person){extra.push('EXISTS(SELECT 1 FROM json_each(p.peopleIds) WHERE value=?)');args.push(person);}if(kind){extra.push('p.kind=?');args.push(kind);}if(saved)extra.push('EXISTS(SELECT 1 FROM feed_saved WHERE postId=p.id AND userId=v.uid)');const rows=await all(base+(extra.length?' AND '+extra.join(' AND '):'')+' ORDER BY p.id DESC LIMIT 21',...params,...args);const pinned=!before&&!author&&!person&&!kind&&!saved?await all(base+' AND p.pinned=1 ORDER BY p.id DESC LIMIT 3',...params):[];return reply({items:rows.slice(0,20).map(decorate),pinned:pinned.map(decorate),hasMore:rows.length>20,before:rows[19]?.id||null,head:rows[0]?.id||0});}
 if(path==='/api/experience/feed'&&method==='POST'){await limit('feed:'+u.id,30,3600000);const b=await read(12*1024*1024),p=await validate(b),clientId=clean(b.clientId,100);assert(/^[\w-]{16,100}$/.test(clientId),400,'Gönderim kimliği geçersiz.');const prior=await one('SELECT id FROM feed_posts WHERE createdBy=? AND clientId=?',u.id,clientId);if(prior)return reply({id:prior.id});assert(p.body||p.photoId||b.image||p.eventId,400,'Bir şey yaz veya fotoğraf ekle.');let filename=null,mime=null;if(b.image){let bytes;try{bytes=Uint8Array.from(atob(String(b.image).split(',').pop()),c=>c.charCodeAt(0));}catch{assert(false,400,'Fotoğraf okunamadı.');}const h=new TextDecoder().decode(bytes.slice(0,12));mime=bytes[0]===255&&bytes[1]===216?'image/jpeg':bytes[0]===137&&h.slice(1,4)==='PNG'?'image/png':h.startsWith('RIFF')&&h.slice(8,12)==='WEBP'?'image/webp':null;assert(mime&&bytes.length>12&&bytes.length<=8*1024*1024,400,'8 MB’tan küçük JPEG, PNG veya WebP seç.');filename='feed/'+crypto.randomUUID();await storage.put(filename,bytes,{httpMetadata:{contentType:mime}});}const time=now();try{await run('INSERT INTO feed_posts(createdBy,clientId,kind,body,date,place,peopleIds,photoId,eventId,filename,mime,visibility,userIds,groupId,createdAt,updatedAt) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',u.id,clientId,p.kind,p.body,p.date,p.place,p.peopleIds,p.photoId,p.eventId,filename,mime,p.visibility,p.userIds,p.groupId,time,time);}catch(e){if(filename)await storage.delete(filename);const retry=await one('SELECT id FROM feed_posts WHERE createdBy=? AND clientId=?',u.id,clientId);if(retry)return reply({id:retry.id});throw e;}const item=await one('SELECT id FROM feed_posts WHERE createdBy=? AND clientId=?',u.id,clientId);await mentions(item.id,p);return reply({id:item.id},201);}
 const media=path.match(/^\/api\/experience\/feed\/media\/(\d+)$/);if(media&&method==='GET'){const p=await get(Number(media[1]));assert(p.filename,404,'Fotoğraf bulunamadı.');const file=await storage.get(p.filename);assert(file,404,'Fotoğraf bulunamadı.');return new Response(file.body,{headers:{'Content-Type':p.mime,'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}});}
 if(path==='/api/experience/feed/notifications'){if(method==='GET'){const rows=await all(base+' AND EXISTS(SELECT 1 FROM feed_notifications WHERE postId=p.id AND userId=v.uid AND readAt IS NULL) ORDER BY p.id DESC LIMIT 30',...params);return reply({items:rows.map(decorate)});}if(method==='POST'){await run('UPDATE feed_notifications SET readAt=? WHERE userId=? AND readAt IS NULL',now(),u.id);return reply({ok:true});}}
 const match=path.match(/^\/api\/experience\/feed\/(\d+)(?:\/(comments|like|save|pin))?$/);if(match){const id=Number(match[1]),p=await get(id),action=match[2];
 if(!action&&method==='GET')return reply(decorate(p));
 if(!action&&method==='PATCH'){assert(p.createdBy===u.id,403,'Yalnızca kendi paylaşımını düzenleyebilirsin.');const b=await read(40000),v=await validate(b);assert(v.body||p.filename||v.photoId||v.eventId,400,'Boş paylaşım kaydedilemez.');await run('UPDATE feed_posts SET kind=?,body=?,date=?,place=?,peopleIds=?,photoId=?,eventId=?,visibility=?,userIds=?,groupId=?,pinned=?,updatedAt=? WHERE id=?',v.kind,v.body,v.date,v.place,v.peopleIds,v.photoId,v.eventId,v.visibility,v.userIds,v.groupId,v.visibility==='family'?p.pinned:0,now(),id);await mentions(id,v);return reply({ok:true});}
 if(!action&&method==='DELETE'){assert(p.createdBy===u.id||u.role!=='member',403,'Bu paylaşımı kaldıramazsın.');await run('UPDATE feed_posts SET deletedAt=?,pinned=0 WHERE id=?',now(),id);return reply({ok:true});}
 if(['like','save'].includes(action)&&['PUT','DELETE'].includes(method)){const table=action==='like'?'feed_reactions':'feed_saved';await run(method==='PUT'?`INSERT OR IGNORE INTO ${table} VALUES(?,?)`:`DELETE FROM ${table} WHERE postId=? AND userId=?`,id,u.id);return reply({ok:true});}
 if(action==='pin'&&method==='PUT'){assert(u.role!=='member',403,'Sabitleme için moderatör yetkisi gerekiyor.');const b=await read(1000);assert(!b.pinned||p.visibility==='family',400,'Yalnızca bütün aileye açık paylaşımlar sabitlenir.');if(b.pinned&&!p.pinned)assert((await one('SELECT COUNT(*) n FROM feed_posts WHERE pinned=1 AND deletedAt IS NULL')).n<3,409,'En fazla üç paylaşım sabitlenebilir.');await run('UPDATE feed_posts SET pinned=? WHERE id=?',b.pinned?1:0,id);return reply({ok:true});}
 if(action==='comments'&&method==='GET'){const after=Math.max(0,Number(url.searchParams.get('after'))||0);const rows=await all('SELECT c.*,u.name author FROM feed_comments c JOIN users u ON u.id=c.createdBy WHERE c.postId=? AND c.deletedAt IS NULL AND c.id>? ORDER BY c.id LIMIT 101',id,after);return reply({items:rows.slice(0,100),hasMore:rows.length>100,after:rows[99]?.id||null});}
 if(action==='comments'&&method==='POST'){await limit('feed-comment:'+u.id,60,60000);const b=await read(20000),body=clean(b.body,4001);assert(body&&body.length<=4000,400,'1–4.000 karakterlik bir cevap yaz.');if(b.parentId)assert(Number.isSafeInteger(b.parentId)&&await one('SELECT id FROM feed_comments WHERE id=? AND postId=? AND deletedAt IS NULL',b.parentId,id),400,'Cevap verilen yorum bulunamadı.');await run('INSERT INTO feed_comments(postId,createdBy,parentId,body,createdAt) VALUES(?,?,?,?,?)',id,u.id,b.parentId||null,body,now());return reply({ok:true},201);}}
 const comment=path.match(/^\/api\/experience\/feed\/comments\/(\d+)$/);if(comment&&method==='DELETE'){const c=await one('SELECT * FROM feed_comments WHERE id=? AND deletedAt IS NULL',Number(comment[1]));assert(c,404,'Yorum bulunamadı.');await get(c.postId);assert(c.createdBy===u.id||u.role!=='member',403,'Bu yorumu kaldıramazsın.');await run('UPDATE feed_comments SET deletedAt=? WHERE id=?',now(),c.id);return reply({ok:true});}
 return reply({error:'İşlem bulunamadı.'},404);
}
