import {assert,clean,validDate} from './domain.mjs';
import {photoVisibleSQL,visiblePhoto} from './archive.mjs';
import {hiddenPeople} from './privacy.mjs';
const now=()=>new Date().toISOString(),uuid=()=>crypto.randomUUID();
export async function memoryInput(b,all,one,u){
 const precision=['day','month','year'].includes(b.datePrecision)?b.datePrecision:'day';let date=b.date;
 if(precision==='year'){assert(/^\d{4}$/.test(date),400,'Dört haneli yıl girin.');date+='-01-01';}else if(precision==='month'){assert(/^\d{4}-\d{2}$/.test(date),400,'Yıl ve ay girin.');date+='-01';}date=validDate(date,false);assert(date<=now().slice(0,10),400,'Fotoğraf tarihi gelecekte olamaz.');
 const place=clean(b.place,200),description=clean(b.description,5000),outsiders=clean(b.outsiders,1000),peopleIds=[...new Set(Array.isArray(b.peopleIds)?b.peopleIds:[])].slice(0,100);assert(place&&description&&(peopleIds.length||outsiders),400,'Yer, hatıra ve fotoğraftaki kişiler zorunlu.');const hidden=await hiddenPeople(all,u);for(const id of peopleIds)assert(!hidden.has(id)&&await one('SELECT id FROM people WHERE id=? AND deletedAt IS NULL',id),400,'Etiketlenecek kişi bulunamadı.');
 const positions=(Array.isArray(b.positions)?b.positions:[]).map(p=>({personId:p.personId,x:Number(p.x),y:Number(p.y)}));assert(positions.length<=100&&positions.every(p=>peopleIds.includes(p.personId)&&Number.isFinite(p.x)&&p.x>=0&&p.x<=100&&Number.isFinite(p.y)&&p.y>=0&&p.y<=100),400,'Fotoğraf işaretleri geçersiz.');
 return{title:clean(b.title,160)||description.slice(0,90),date,place,description,outsiders,peopleIds,datePrecision:precision,source:clean(b.source,500),photographer:clean(b.photographer,200),positions};
}
// Upgrade old feed media in bounded, idempotent batches without copying media or inventing its story.
async function importLegacy({all,batch,u}){
 const rows=await all("SELECT * FROM feed_posts WHERE photoId IS NULL AND filename IS NOT NULL AND deletedAt IS NULL AND (createdBy=? OR ?='owner') ORDER BY id LIMIT 30",u.id,u.role);
 for(const p of rows){const id='legacy-feed-'+p.id;await batch([
  ['INSERT OR IGNORE INTO photos VALUES(?,?,?,?,?,?,?,?,?,?,NULL)',id,'Hayat’tan bir fotoğraf',p.date,p.place||'','',p.filename,p.mime,p.createdBy,'approved',p.createdAt],
  ['INSERT OR IGNORE INTO photo_privacy VALUES(?,?)',id,p.visibility==='private'?'private':'family'],
  ['INSERT OR IGNORE INTO content_audience VALUES(?,?,?,?,?)','photo',id,p.visibility,p.userIds,p.groupId],
  ['INSERT OR IGNORE INTO photo_people(photoId,personId) SELECT ?,people.id FROM people WHERE id IN(SELECT value FROM json_each(?))',id,p.peopleIds],
  ['UPDATE feed_posts SET photoId=?,filename=NULL,mime=NULL WHERE id=? AND photoId IS NULL',id,p.id]
 ]);}
 return rows.length;
}
export async function memories(ctx){const{path,method,url,u,read,all,one,run,batch,storage,limit}=ctx;const reply=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store'}});
 const root='/api/experience/memories';const params=[u.id,u.role,u.id,u.id,u.id];const where=`p.deletedAt IS NULL AND (p.status='approved' OR p.createdBy=? OR ?!='member') AND ${photoVisibleSQL.replaceAll('photos.', 'p.')}`;
 async function decorate(p){const details=await one('SELECT * FROM photo_details WHERE photoId=?',p.id),tags=await all('SELECT personId FROM photo_people WHERE photoId=?',p.id);return{...p,filename:undefined,mime:undefined,url:'/media/'+p.id,peopleIds:tags.map(x=>x.personId),datePrecision:details?.datePrecision||'day',outsiders:details?.outsiders||'',source:details?.source||'',photographer:details?.photographer||'',positions:JSON.parse(details?.positions||'[]'),albumId:details?.albumId||null};}
 if(path===root&&method==='GET'){await importLegacy(ctx);const offset=Math.max(0,Number(url.searchParams.get('offset'))||0),year=url.searchParams.get('year'),person=url.searchParams.get('person'),author=url.searchParams.get('author'),album=url.searchParams.get('album');let extra='',args=[];if(year){assert(/^\d{4}$/.test(year),400,'Yıl geçersiz.');extra+=' AND substr(p.date,1,4)=?';args.push(year);}if(person){extra+=' AND EXISTS(SELECT 1 FROM photo_people WHERE photoId=p.id AND personId=?)';args.push(person);}if(author){extra+=' AND p.createdBy=?';args.push(author);}if(album){extra+=' AND d.albumId=?';args.push(album);}const rows=await all(`SELECT p.* FROM photos p LEFT JOIN photo_details d ON d.photoId=p.id WHERE ${where}${extra} ORDER BY p.date DESC,p.id DESC LIMIT 61 OFFSET ?`,...params,...args,offset);const years=await all(`SELECT DISTINCT substr(p.date,1,4) year FROM photos p WHERE ${where} AND p.date IS NOT NULL ORDER BY year DESC`,...params);return reply({items:await Promise.all(rows.slice(0,60).map(decorate)),hasMore:rows.length>60,offset:offset+60,years:years.map(x=>x.year)});}
 if(path===root+'/duplicates'&&method==='POST'){const b=await read(2000);assert(/^[a-f0-9]{64}$/.test(b.digest),400,'Dosya özeti geçersiz.');const rows=await all(`SELECT p.* FROM photos p JOIN photo_details d ON d.photoId=p.id WHERE ${where} AND d.digest=? LIMIT 10`,...params,b.digest);return reply({items:await Promise.all(rows.map(decorate))});}
 if(path===root&&method==='POST'){await limit('memory:'+u.id,30,3600000);const b=await read(45*1024*1024),clientId=clean(b.clientId,100)||uuid();assert(/^[\w-]{16,100}$/.test(clientId),400,'Gönderim kimliği geçersiz.');const previous=await one('SELECT photoId,albumId FROM photo_details WHERE createdBy=? AND clientId=?',u.id,clientId+':0');if(previous)return reply({id:previous.photoId,albumId:previous.albumId});
 const input=Array.isArray(b.photos)?b.photos:[b];assert(input.length>0&&input.length<=8,400,'Bir albümde 1–8 fotoğraf seçin.');const mode=['family','private','selected','group'].includes(b.visibility)?b.visibility:'family',users=[...new Set(Array.isArray(b.userIds)?b.userIds:[])].slice(0,200);if(mode==='selected'){assert(users.length,400,'Görünürlük için üye seçin.');for(const id of users)assert(await one('SELECT id FROM users WHERE id=? AND active=1',id),400,'Üye bulunamadı.');}if(mode==='group')assert(await one('SELECT groupId FROM group_members WHERE groupId=? AND userId=?',b.groupId,u.id),400,'Üyesi olduğun grup seç.');
 const albumId=uuid(),items=[];for(let i=0;i<input.length;i++){const v=input[i],m=await memoryInput(v,all,one,u);let bytes;try{bytes=Uint8Array.from(atob(String(v.data||v.image||'').split(',').pop()),c=>c.charCodeAt(0));}catch{assert(false,400,'Fotoğraf okunamadı.');}const head=new TextDecoder().decode(bytes.slice(0,12)),mime=bytes[0]===255&&bytes[1]===216?'image/jpeg':bytes[0]===137&&head.slice(1,4)==='PNG'?'image/png':head.startsWith('RIFF')&&head.slice(8,12)==='WEBP'?'image/webp':null;assert(mime&&bytes.length>12&&bytes.length<=8*1024*1024,400,'8 MB’tan küçük JPEG, PNG veya WebP seçin.');const digest=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))).map(x=>x.toString(16).padStart(2,'0')).join('');items.push({...m,id:uuid(),filename:'memories/'+uuid(),mime,bytes,digest});}
 const statements=[],time=now(),status=b.share?'approved':u.role==='member'?'pending':'approved';for(let i=0;i<items.length;i++){const p=items[i];statements.push(['INSERT INTO photos VALUES(?,?,?,?,?,?,?,?,?,?,NULL)',p.id,p.title,p.date,p.place,p.description,p.filename,p.mime,u.id,status,time],['INSERT INTO photo_details VALUES(?,?,?,?,?,?,?,?,?,?)',p.id,p.datePrecision,p.outsiders,p.source,p.photographer,JSON.stringify(p.positions),p.digest,albumId,clientId+':'+i,u.id],['INSERT INTO photo_privacy VALUES(?,?)',p.id,mode==='private'?'private':'family'],['INSERT INTO content_audience VALUES(?,?,?,?,?)','photo',p.id,mode,JSON.stringify(users),mode==='group'?b.groupId:null],...p.peopleIds.map(id=>['INSERT INTO photo_people VALUES(?,?)',p.id,id]));}
 if(b.share){const people=[...new Set(items.flatMap(p=>p.peopleIds))];statements.push(['INSERT INTO feed_posts(createdBy,clientId,kind,body,date,place,peopleIds,photoId,visibility,userIds,groupId,createdAt,updatedAt) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)',u.id,clientId,'post',clean(b.body,6000),null,'',JSON.stringify(people),items[0].id,mode,JSON.stringify(users),mode==='group'?b.groupId:null,time,time]);}
 if(b.share){const ids=[...new Set(items.flatMap(p=>p.peopleIds))];if(ids.length)statements.push(['INSERT OR IGNORE INTO feed_notifications(postId,userId) SELECT p.id,d.userId FROM feed_posts p JOIN profile_details d ON d.personId IN(SELECT value FROM json_each(?)) WHERE p.createdBy=? AND p.clientId=? AND d.userId IS NOT NULL AND d.userId!=?',JSON.stringify(ids),u.id,clientId,u.id]);}
 const uploaded=[];try{for(const p of items){await storage.put(p.filename,p.bytes,{httpMetadata:{contentType:p.mime}});uploaded.push(p.filename);}await batch(statements);}catch(e){for(const f of uploaded)await storage.delete(f);const retry=await one('SELECT photoId,albumId FROM photo_details WHERE createdBy=? AND clientId=?',u.id,clientId+':0');if(retry)return reply({id:retry.photoId,albumId:retry.albumId});throw e;}return reply({id:items[0].id,ids:items.map(p=>p.id),albumId,status},201);}
 const m=path.match(/^\/api\/experience\/memories\/([\w-]+)(?:\/(suggestions|audio|related))?$/);if(m){const id=m[1],p=await visiblePhoto(one,u,id);assert(p,404,'Fotoğraf bulunamadı.');const canEdit=p.createdBy===u.id||u.role!=='member';
 if(!m[2]&&method==='GET'){const suggestions=await all('SELECT s.*,u.name author FROM photo_suggestions s JOIN users u ON u.id=s.createdBy WHERE s.photoId=? AND (s.createdBy=? OR ?=1) ORDER BY s.createdAt DESC LIMIT 100',id,u.id,canEdit?1:0),audio=await one('SELECT transcript FROM photo_audio WHERE photoId=?',id);return reply({...await decorate(p),canEdit,suggestions:suggestions.map(s=>({...s,data:JSON.parse(s.data)})),audio:audio?{url:root+'/'+id+'/audio',transcript:audio.transcript}:null});}
 if(!m[2]&&method==='PATCH'){assert(canEdit,403,'Düzenleme yetkin yok.');const b=await read(30000),v=await memoryInput(b,all,one,u);await batch(update(id,v));return reply({ok:true});}
 if(m[2]==='related'&&method==='GET'){const rows=await all(`SELECT p.* FROM photos p WHERE ${where} AND p.id!=? AND (p.place=? OR EXISTS(SELECT 1 FROM photo_people a JOIN photo_people b ON a.personId=b.personId WHERE a.photoId=p.id AND b.photoId=?)) ORDER BY p.date DESC LIMIT 8`,...params,id,p.place,id);return reply({items:await Promise.all(rows.map(decorate))});}
 if(m[2]==='suggestions'&&method==='POST'){await limit('suggest:'+u.id,30,3600000);const b=await read(30000),v=await memoryInput(b,all,one,u);await run('INSERT INTO photo_suggestions VALUES(?,?,?,?,?,?,NULL,NULL)',uuid(),id,u.id,JSON.stringify(v),'pending',now());return reply({ok:true},201);}
 if(m[2]==='suggestions'&&method==='PATCH'){assert(canEdit,403,'Öneriyi yalnızca fotoğraf sahibi veya moderatör değerlendirebilir.');const b=await read(2000),s=await one("SELECT * FROM photo_suggestions WHERE id=? AND photoId=? AND status='pending'",b.id,id);assert(s,404,'Bekleyen öneri bulunamadı.');assert(['approved','rejected'].includes(b.status),400,'Karar geçersiz.');const raw=JSON.parse(s.data);if(raw.datePrecision==='year')raw.date=raw.date.slice(0,4);else if(raw.datePrecision==='month')raw.date=raw.date.slice(0,7);const v=await memoryInput(raw,all,one,u);await batch([...(b.status==='approved'?update(id,v):[]),['UPDATE photo_suggestions SET status=?,reviewedBy=?,reviewedAt=? WHERE id=?',b.status,u.id,now(),s.id]]);return reply({ok:true});}
 if(m[2]==='audio'){if(method==='GET'){const a=await one('SELECT * FROM photo_audio WHERE photoId=?',id);assert(a,404,'Ses kaydı yok.');const f=await storage.get(a.filename);assert(f,404,'Ses kaydı bulunamadı.');return new Response(f.body,{headers:{'Content-Type':a.mime,'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}});}assert(canEdit,403,'Ses kaydını yalnızca fotoğraf yetkilisi düzenleyebilir.');if(method==='PUT'){const b=await read(15*1024*1024);assert(['audio/webm','audio/mp4','audio/ogg','audio/mpeg','audio/wav'].includes(b.mime),400,'Ses biçimi desteklenmiyor.');let bytes;try{bytes=Uint8Array.from(atob(String(b.data).split(',').pop()),c=>c.charCodeAt(0));}catch{assert(false,400,'Ses okunamadı.');}assert(bytes.length>10&&bytes.length<=10*1024*1024,400,'Ses en fazla 10 MB olabilir.');const head=new TextDecoder().decode(bytes.slice(0,12));const valid=b.mime==='audio/webm'?bytes[0]===0x1a&&bytes[1]===0x45&&bytes[2]===0xdf&&bytes[3]===0xa3:b.mime==='audio/mp4'?head.slice(4,8)==='ftyp':b.mime==='audio/ogg'?head.startsWith('OggS'):b.mime==='audio/wav'?head.startsWith('RIFF')&&head.slice(8,12)==='WAVE':head.startsWith('ID3')||bytes[0]===255&&(bytes[1]&224)===224;assert(valid,400,'Dosyanın içeriği seçilen ses biçimiyle eşleşmiyor.');const old=await one('SELECT filename FROM photo_audio WHERE photoId=?',id),filename='voices/'+uuid();await storage.put(filename,bytes,{httpMetadata:{contentType:b.mime}});try{await run('INSERT INTO photo_audio VALUES(?,?,?,?,?) ON CONFLICT(photoId) DO UPDATE SET filename=excluded.filename,mime=excluded.mime,transcript=excluded.transcript',id,filename,b.mime,clean(b.transcript,10000),u.id);}catch(e){await storage.delete(filename);throw e;}if(old)await storage.delete(old.filename);return reply({ok:true});}if(method==='PATCH'){const b=await read(15000);await run('UPDATE photo_audio SET transcript=? WHERE photoId=?',clean(b.transcript,10000),id);return reply({ok:true});}}
 }
 function update(id,v){return[['UPDATE photos SET title=?,date=?,place=?,description=? WHERE id=?',v.title,v.date,v.place,v.description,id],['INSERT INTO photo_details(photoId,datePrecision,outsiders,source,photographer,positions) VALUES(?,?,?,?,?,?) ON CONFLICT(photoId) DO UPDATE SET datePrecision=excluded.datePrecision,outsiders=excluded.outsiders,source=excluded.source,photographer=excluded.photographer,positions=excluded.positions',id,v.datePrecision,v.outsiders,v.source,v.photographer,JSON.stringify(v.positions)],['DELETE FROM photo_people WHERE photoId=?',id],...v.peopleIds.map(x=>['INSERT INTO photo_people VALUES(?,?)',id,x])];}
 return reply({error:'İşlem bulunamadı.'},404);
}
