import {assert,clean} from './domain.mjs';
const enc=new TextEncoder(),b64=b=>btoa(String.fromCharCode(...b)),un64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
const hash=async s=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(s))),x=>x.toString(16).padStart(2,'0')).join('');
const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
export function base32(bytes){let bits=0,value=0,out='';for(const b of bytes){value=(value<<8)|b;bits+=8;while(bits>=5){out+=alphabet[(value>>>(bits-5))&31];bits-=5;}}if(bits)out+=alphabet[(value<<(5-bits))&31];return out;}
function un32(s){let bits=0,value=0,out=[];for(const c of s){value=(value<<5)|alphabet.indexOf(c);bits+=5;if(bits>=8){out.push((value>>>(bits-8))&255);bits-=8;}}return new Uint8Array(out);}
export async function totp(secret,step=Math.floor(Date.now()/30000)){const b=new Uint8Array(8);new DataView(b.buffer).setBigUint64(0,BigInt(step));const k=await crypto.subtle.importKey('raw',un32(secret),{name:'HMAC',hash:'SHA-1'},false,['sign']);const h=new Uint8Array(await crypto.subtle.sign('HMAC',k,b)),o=h.at(-1)&15;return String((((h[o]&127)<<24)|(h[o+1]<<16)|(h[o+2]<<8)|h[o+3])%1000000).padStart(6,'0');}
async function crypt(secret,keyText,decode=false){const key=await crypto.subtle.importKey('raw',await crypto.subtle.digest('SHA-256',enc.encode(keyText)),{name:'AES-GCM'},false,['encrypt','decrypt']);if(decode){const [iv,cipher]=secret.split('.');return new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:un64(iv)},key,un64(cipher)));}const iv=crypto.getRandomValues(new Uint8Array(12));return b64(iv)+'.'+b64(new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},key,enc.encode(secret))));}
export async function securityGate({u,path,token,one}){if(path.startsWith('/api/security/')||path==='/api/me'||path==='/api/logout')return;const f=await one('SELECT enabled FROM security_factors WHERE userId=?',u.id);if(f?.enabled){assert(token&&await one('SELECT token FROM security_sessions WHERE token=? AND userId=? AND expires>?',await hash(token),u.id,Date.now()),428,'İki aşamalı doğrulama kodunu girin.');}}
export async function security({u,path,method,read,one,run,batch,limit,keyText}){assert(keyText,503,'İki aşamalı doğrulama anahtarı yapılandırılmamış.');const reply=x=>new Response(JSON.stringify(x),{headers:{'Content-Type':'application/json','Cache-Control':'no-store'}});const f=await one('SELECT * FROM security_factors WHERE userId=?',u.id);
 if(path==='/api/security/status'&&method==='GET')return reply({enabled:!!f?.enabled});
 if(path==='/api/security/setup'&&method==='POST'){assert(!f?.enabled,409,'Doğrulama zaten etkin.');const secret=base32(crypto.getRandomValues(new Uint8Array(20)));await run('INSERT OR REPLACE INTO security_factors VALUES(?,?,0,-1)',u.id,await crypt(secret,keyText));return reply({secret,uri:'otpauth://totp/'+encodeURIComponent('Saricicek:'+u.email)+'?secret='+secret+'&issuer=Saricicek&algorithm=SHA1&digits=6&period=30'});}
 if(['/api/security/enable','/api/security/verify','/api/security/disable'].includes(path)&&method==='POST'){await limit('totp:'+u.id,8,300000);assert(f,400,'Önce doğrulama kurulumunu başlatın.');const b=await read(2000),code=clean(b.code,6);assert(/^\d{6}$/.test(code),400,'Altı haneli kodu yazın.');const secret=await crypt(f.secret,keyText,true),current=Math.floor(Date.now()/30000);let matched=-1;for(const step of [current-1,current,current+1])if(step>f.lastStep&&await totp(secret,step)===code)matched=step;assert(matched>=0,403,'Kod yanlış, kullanılmış veya süresi dolmuş. Yeni kodu deneyin.');assert(path!=='/api/security/verify'||f.enabled,400,'Doğrulama etkin değil.');const result=await run('UPDATE security_factors SET lastStep=? WHERE userId=? AND lastStep<?',matched,u.id,matched);assert((result.meta?.changes??result.changes)===1,403,'Bu kod zaten kullanıldı.');if(path==='/api/security/disable'){await batch([['DELETE FROM security_sessions WHERE userId=?',u.id],['DELETE FROM security_factors WHERE userId=?',u.id]]);return reply({ok:true});}if(path==='/api/security/enable')await run('UPDATE security_factors SET enabled=1 WHERE userId=?',u.id);const token=crypto.randomUUID()+crypto.randomUUID();await run('INSERT INTO security_sessions VALUES(?,?,?)',await hash(token),u.id,Date.now()+8*3600000);await run('DELETE FROM security_sessions WHERE expires<?',Date.now());const response=reply({token});response.headers.set('Set-Cookie','sf_factor='+token+'; HttpOnly; SameSite=Strict; Path=/; Max-Age=28800; Secure');return response;}
 assert(false,404,'Doğrulama işlemi bulunamadı.');}
