import {community,communityPath} from './community.mjs';
import http from 'node:http';
import {readFile,writeFile,mkdir,stat,unlink} from 'node:fs/promises';
import {resolve,extname,basename} from 'node:path';
import {randomUUID} from 'node:crypto';
import {db,all,one,run,transaction,audit,dataDir} from './db.mjs';
import {token,hash,passwordHash,passwordVerify,cookie} from './auth.mjs';
import {assert,clean,validDate,personInput,validateRelation} from './domain.mjs';
const port=Number(process.env.PORT||3000), origin=process.env.APP_ORIGIN||`http://localhost:${port}`,production=process.env.NODE_ENV==='production';
if(production && !origin.startsWith('https://')) throw Error('Production requires HTTPS APP_ORIGIN.');
const publicDir=resolve('public'),uploadDir=resolve(dataDir,'uploads');await mkdir(uploadDir,{recursive:true});
const now=()=>new Date().toISOString(), publicUser=u=>({id:u.id,name:u.name,email:u.email,role:u.role,active:u.active});
const staff=u=>assert(u.role==='owner'||u.role==='moderator',403,'Bu işlem için moderatör yetkisi gerekiyor.');
const owner=u=>assert(u.role==='owner',403,'Bu işlem yalnızca aile yöneticisine açık.');
function limit(key,max=10,ms=900000){const item=one('SELECT * FROM throttle WHERE key=?',key);if(!item||item.expires<Date.now())run('INSERT OR REPLACE INTO throttle VALUES(?,?,?)',key,1,Date.now()+ms);else{assert(item.count<max,429,'Çok fazla deneme. Lütfen daha sonra tekrar deneyin.');run('UPDATE throttle SET count=count+1 WHERE key=?',key);}}
async function body(req,max=12*1024*1024){let chunks=[],size=0;for await(const c of req){size+=c.length;assert(size<=max,413,'Dosya veya istek çok büyük.');chunks.push(c);}try{return JSON.parse(Buffer.concat(chunks).toString()||'{}');}catch{assert(false,400,'İstek biçimi geçersiz.');}}
function json(res,status,data){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(data));}
function createSession(res,u){const raw=token(),csrf=token();run('INSERT INTO sessions VALUES(?,?,?,?)',hash(raw),u.id,csrf,Date.now()+7*86400000);res.setHeader('Set-Cookie',`sf_session=${raw}; HttpOnly; SameSite=Lax; Path=/; Max-Age=604800${production?'; Secure':''}`);return{user:publicUser(u),csrf};}
function settings(){return Object.fromEntries(all('SELECT * FROM settings').map(x=>[x.key,x.value]));}
function authorize(req){const sid=cookie(req.headers.cookie).sf_session;const session=sid&&one('SELECT * FROM sessions WHERE token=? AND expires>?',hash(sid),Date.now());assert(session,401,'Oturum açmanız gerekiyor.');const u=one('SELECT * FROM users WHERE id=? AND active=1',session.userId);assert(u,401,'Hesap kullanılamıyor.');if(!['GET','HEAD'].includes(req.method))assert(req.headers['x-csrf-token']===session.csrf,403,'Oturum doğrulaması başarısız. Sayfayı yenileyin.');return{u,session};}
function imageType(b){if(b.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])))return['png','image/png'];if(b[0]===255&&b[1]===216&&b[2]===255)return['jpg','image/jpeg'];if(b.toString('ascii',0,4)==='RIFF'&&b.toString('ascii',8,12)==='WEBP')return['webp','image/webp'];return null;}
async function handler(req,res){
 res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','same-origin');res.setHeader('X-Frame-Options','DENY');
 res.setHeader('Content-Security-Policy',"default-src 'self'; img-src 'self' data: blob: https://tile.openstreetmap.org; style-src 'self' 'unsafe-inline'; script-src 'self'; connect-src 'self'; base-uri 'none'; frame-ancestors 'none'; form-action 'self'");
 if(production)res.setHeader('Strict-Transport-Security','max-age=31536000; includeSubDomains');
 try{
 const url=new URL(req.url,origin),path=url.pathname,method=req.method;
 if(path==='/health')return json(res,200,{ok:true});
 if(path.startsWith('/api/')&&!['GET','HEAD'].includes(method)){assert(req.headers.origin===origin,403,'İstek kaynağı doğrulanamadı.');assert((req.headers['content-type']||'').startsWith('application/json'),415,'JSON içerik gerekiyor.');}
 if(path==='/api/login'&&method==='POST'){
  limit('login-ip:'+req.socket.remoteAddress,40);const b=await body(req,4096),email=clean(b.email).toLowerCase();limit('login:'+email,10);
  const u=one('SELECT * FROM users WHERE email=? AND active=1',email);const fallback='00'.repeat(32)+':'+ '00'.repeat(64);
  const valid=await passwordVerify(b.password,u?.password||fallback);assert(u&&valid,401,'E-posta veya şifre hatalı.');audit(u.id,'Giriş yapıldı');return json(res,200,createSession(res,u));
 }
 if(path==='/api/accept-invite'&&method==='POST'){
  limit('accept:'+req.socket.remoteAddress,20);const b=await body(req,4096),p=await passwordHash(b.password),name=clean(b.name,120);assert(name.length>1,400,'Ad soyad girin.');
  const u=transaction(()=>{const invite=one('SELECT * FROM invites WHERE token=? AND used=0 AND expires>?',hash(clean(b.token,100)),Date.now());assert(invite,400,'Davet geçersiz veya süresi dolmuş.');assert(!one('SELECT id FROM users WHERE email=?',invite.email),409,'Bu e-posta zaten kayıtlı.');const id=randomUUID();run('INSERT INTO users VALUES(?,?,?,?,?,?,?)',id,name,invite.email,p,invite.role,1,now());run('UPDATE invites SET used=1 WHERE id=?',invite.id);audit(id,'Davet kabul edildi');return one('SELECT * FROM users WHERE id=?',id);});return json(res,201,createSession(res,u));
 }
 if(path==='/api/reset-password'&&method==='POST'){
  limit('reset:'+req.socket.remoteAddress,15);const b=await body(req,4096),p=await passwordHash(b.password);transaction(()=>{const r=one('SELECT * FROM resets WHERE token=? AND used=0 AND expires>?',hash(clean(b.token,100)),Date.now());assert(r,400,'Bağlantı geçersiz veya süresi dolmuş.');run('UPDATE users SET password=? WHERE id=?',p,r.userId);run('DELETE FROM sessions WHERE userId=?',r.userId);run('UPDATE resets SET used=1 WHERE token=?',r.token);audit(r.userId,'Şifre yenilendi');});return json(res,200,{ok:true});
 }
 if(path==='/api/config'&&method==='GET')return json(res,200,{demo:process.env.DEMO_MODE==='1',configured:!!one('SELECT id FROM users LIMIT 1')});
 if(path.startsWith('/api/')||path.startsWith('/media/')||path.startsWith('/document/')){
  const {u,session}=authorize(req);
  if(communityPath(path)){const storage={async put(key,bytes){const file=resolve(uploadDir,key);await mkdir(resolve(file,'..'),{recursive:true});await writeFile(file,bytes);},async get(key){try{return{body:await readFile(resolve(uploadDir,key))};}catch{return null;}},async delete(key){await unlink(resolve(uploadDir,key)).catch(()=>{});}};const r=await community({path,method,url,u,read:max=>body(req,max),all,one,run,batch:items=>transaction(()=>items.map(([sql,...args])=>run(sql,...args))),storage,limit});res.writeHead(r.status,Object.fromEntries(r.headers));return res.end(Buffer.from(await r.arrayBuffer()));}
  if(path==='/api/me')return json(res,200,{user:publicUser(u),csrf:session.csrf});
  if(path==='/api/logout'&&method==='POST'){run('DELETE FROM sessions WHERE token=?',session.token);res.setHeader('Set-Cookie','sf_session=; Path=/; HttpOnly; SameSite=Lax; Max-Age=0');return json(res,200,{ok:true});}
  if(path==='/api/bootstrap'&&method==='GET')return json(res,200,{
   user:publicUser(u),settings:settings(),people:all('SELECT * FROM people WHERE deletedAt IS NULL ORDER BY name'),relations:all('SELECT r.* FROM relations r JOIN people a ON a.id=r.personA JOIN people b ON b.id=r.personB WHERE a.deletedAt IS NULL AND b.deletedAt IS NULL'),
   photos:all(`SELECT id,title,date,place,description,createdBy,status,createdAt FROM photos WHERE deletedAt IS NULL AND (status='approved' OR createdBy=? OR ?!='member') ORDER BY createdAt DESC,id DESC LIMIT 200`,u.id,u.role).map(p=>({...p,url:'/media/'+p.id,peopleIds:all('SELECT personId FROM photo_people WHERE photoId=?',p.id).map(x=>x.personId)})),
   events:all(`SELECT * FROM events WHERE deletedAt IS NULL AND (status='approved' OR createdBy=? OR ?!='member') ORDER BY date DESC LIMIT 1000`,u.id,u.role),
   photoCount:one(`SELECT COUNT(*) n FROM photos WHERE deletedAt IS NULL AND status='approved'`).n,
  });
  if(path==='/api/people'&&method==='POST'){staff(u);const b=personInput(await body(req,16000)),id=randomUUID(),date=now();run('INSERT INTO people VALUES(?,?,?,?,?,?,?,?,?,?,?,NULL)',id,b.name,b.birthDate,b.deathDate,b.place,b.country,b.biography,b.source,u.id,date,date);audit(u.id,'Kişi eklendi',id);return json(res,201,{id});}
  const personMatch=path.match(/^\/api\/people\/([\w-]+)$/);
  if(personMatch){staff(u);const id=personMatch[1];assert(one('SELECT id FROM people WHERE id=? AND deletedAt IS NULL',id),404,'Kişi bulunamadı.');if(method==='PATCH'){const b=personInput(await body(req,16000));run('UPDATE people SET name=?,birthDate=?,deathDate=?,place=?,country=?,biography=?,source=?,updatedAt=? WHERE id=?',b.name,b.birthDate,b.deathDate,b.place,b.country,b.biography,b.source,now(),id);audit(u.id,'Kişi güncellendi',id);return json(res,200,{ok:true});}if(method==='DELETE'){run('UPDATE people SET deletedAt=? WHERE id=?',now(),id);audit(u.id,'Kişi arşivden kaldırıldı',id);return json(res,200,{ok:true});}}
  if(path==='/api/relations'&&method==='POST'){staff(u);const b=await body(req,4096);assert(one('SELECT id FROM people WHERE id=? AND deletedAt IS NULL',b.personA)&&one('SELECT id FROM people WHERE id=? AND deletedAt IS NULL',b.personB),400,'Her iki kişiyi de seçin.');validateRelation(all('SELECT * FROM relations'),b.personA,b.personB,b.type);const id=randomUUID();run('INSERT INTO relations VALUES(?,?,?,?,?)',id,b.personA,b.personB,b.type,validDate(b.date));audit(u.id,'Aile bağı eklendi',id);return json(res,201,{id});}
  if(path.match(/^\/api\/relations\/[\w-]+$/)&&method==='DELETE'){staff(u);const id=path.split('/').pop();run('DELETE FROM relations WHERE id=?',id);audit(u.id,'Aile bağı kaldırıldı',id);return json(res,200,{ok:true});}
  if(path==='/api/photos'&&method==='GET'){
   const offset=Math.max(0,Math.min(100000,Number(url.searchParams.get('offset'))||0));
   const items=all(`SELECT id,title,date,place,description,createdBy,status,createdAt FROM photos WHERE deletedAt IS NULL AND (status='approved' OR createdBy=? OR ?!='member') ORDER BY createdAt DESC,id DESC LIMIT 101 OFFSET ?`,u.id,u.role,offset);
   return json(res,200,{items:items.slice(0,100).map(p=>({...p,url:'/media/'+p.id,peopleIds:all('SELECT personId FROM photo_people WHERE photoId=?',p.id).map(x=>x.personId)})),hasMore:items.length>100});
  }
  if(path==='/api/photos'&&method==='POST'){
   limit('upload:'+u.id,50,3600000);const b=await body(req),title=clean(b.title,160);assert(title,400,'Fotoğraf başlığı girin.');assert(typeof b.data==='string',400,'Fotoğraf seçin.');const bytes=Buffer.from(b.data.replace(/^data:image\/[\w+.-]+;base64,/,''),'base64'),type=imageType(bytes);assert(type&&bytes.length<=8*1024*1024,400,'En fazla 8 MB boyutunda JPEG, PNG veya WebP yükleyin.');const date=validDate(b.date),ids=Array.isArray(b.peopleIds)?[...new Set(b.peopleIds)].slice(0,100):[];for(const id of ids)assert(one('SELECT id FROM people WHERE id=? AND deletedAt IS NULL',id),400,'Etiketlenen kişi bulunamadı.');const id=randomUUID(),filename=id+'.'+type[0];await writeFile(resolve(uploadDir,filename),bytes,{flag:'wx'});
   transaction(()=>{run('INSERT INTO photos VALUES(?,?,?,?,?,?,?,?,?,?,NULL)',id,title,date,clean(b.place),clean(b.description,5000),filename,type[1],u.id,u.role==='member'?'pending':'approved',now());for(const p of ids)run('INSERT INTO photo_people VALUES(?,?)',id,p);audit(u.id,'Fotoğraf yüklendi',id);});return json(res,201,{id,status:u.role==='member'?'pending':'approved'});
  }
  if(path==='/api/events'&&method==='POST'){const b=await body(req,16000),title=clean(b.title,160);assert(title,400,'Başlık girin.');assert(['gathering','birthday','marriage','memorial','funeral','migration','story'].includes(b.type),400,'Olay türünü seçin.');const date=validDate(b.date,false),personId=b.personId||null;assert(!personId||one('SELECT id FROM people WHERE id=? AND deletedAt IS NULL',personId),400,'Kişi bulunamadı.');const id=randomUUID();run('INSERT INTO events VALUES(?,?,?,?,?,?,?,?,?,?,NULL)',id,title,b.type,date,clean(b.place),clean(b.description,5000),personId,u.id,u.role==='member'?'pending':'approved',now());audit(u.id,'Aile olayı eklendi',id);return json(res,201,{id});}
  const content=path.match(/^\/api\/(photos|events)\/([\w-]+)$/);
  if(content&&method==='PATCH'){const [,table,id]=content,b=await body(req,16000),item=one(`SELECT * FROM ${table} WHERE id=? AND deletedAt IS NULL`,id);assert(item,404,'Kayıt bulunamadı.');assert(u.role!=='member'||item.createdBy===u.id,403,'Bu kaydı düzenleyemezsiniz.');if(b.status){staff(u);assert(['approved','rejected'].includes(b.status),400,'Durum geçersiz.');run(`UPDATE ${table} SET status=? WHERE id=?`,b.status,id);audit(u.id,'İçerik '+b.status,id);}else{const title=clean(b.title,160);assert(title,400,'Başlık girin.');run(`UPDATE ${table} SET title=?,description=?,place=?,date=?,status=? WHERE id=?`,title,clean(b.description,5000),clean(b.place),validDate(b.date,table==='photos'),u.role==='member'?'pending':item.status,id);audit(u.id,'İçerik düzenlendi',id);}return json(res,200,{ok:true});}
  if(content&&method==='DELETE'){const [,table,id]=content,item=one(`SELECT * FROM ${table} WHERE id=? AND deletedAt IS NULL`,id);assert(item,404,'Kayıt bulunamadı.');assert(u.role!=='member'||item.createdBy===u.id,403,'Bu kaydı kaldıramazsınız.');run(`UPDATE ${table} SET deletedAt=? WHERE id=?`,now(),id);audit(u.id,'İçerik kaldırıldı',id);return json(res,200,{ok:true});}
  if(path.startsWith('/media/')&&method==='GET'){const p=one('SELECT * FROM photos WHERE id=? AND deletedAt IS NULL',path.slice(7));assert(p&&(p.status==='approved'||p.createdBy===u.id||u.role!=='member'),404,'Fotoğraf bulunamadı.');const bytes=await readFile(resolve(uploadDir,basename(p.filename)));res.writeHead(200,{'Content-Type':p.mime,'Cache-Control':'private, no-store'});return res.end(bytes);}
  if(path==='/api/admin'&&method==='GET'){staff(u);return json(res,200,{users:u.role==='owner'?all('SELECT id,name,email,role,active,createdAt FROM users'):[],invites:u.role==='owner'?all('SELECT id,email,role,expires,used FROM invites ORDER BY expires DESC'):[],audit:all('SELECT a.*,u.name FROM audit a LEFT JOIN users u ON u.id=a.userId ORDER BY a.id DESC LIMIT 100'),trash:{people:all('SELECT id,name,deletedAt FROM people WHERE deletedAt IS NOT NULL'),photos:all('SELECT id,title,deletedAt FROM photos WHERE deletedAt IS NOT NULL'),events:all('SELECT id,title,deletedAt FROM events WHERE deletedAt IS NOT NULL')}});}
  if(path==='/api/invites'&&method==='POST'){owner(u);const b=await body(req,4096),email=clean(b.email).toLowerCase();assert(/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email),400,'Geçerli e-posta girin.');assert(['member','moderator'].includes(b.role),400,'Rol geçersiz.');assert(!one('SELECT id FROM users WHERE email=?',email),409,'Üye zaten kayıtlı.');const raw=token(),id=randomUUID();run('INSERT INTO invites VALUES(?,?,?,?,?,?,?)',id,email,b.role,hash(raw),Date.now()+7*86400000,0,u.id);audit(u.id,'Davet oluşturuldu',id);return json(res,201,{url:origin+'/#invite='+raw,email});}
  if(path.match(/^\/api\/invites\/[\w-]+$/)&&method==='DELETE'){owner(u);run('DELETE FROM invites WHERE id=?',path.split('/').pop());return json(res,200,{ok:true});}
  const userMatch=path.match(/^\/api\/users\/([\w-]+)$/);
  if(userMatch&&method==='PATCH'){owner(u);const id=userMatch[1],target=one('SELECT * FROM users WHERE id=?',id);assert(target&&target.role!=='owner',400,'Kurucu hesabı bu ekrandan değiştirilemez.');const b=await body(req,4096);assert(['member','moderator'].includes(b.role)&&[0,1].includes(b.active),400,'Rol veya durum geçersiz.');run('UPDATE users SET role=?,active=? WHERE id=?',b.role,b.active,id);run('DELETE FROM sessions WHERE userId=?',id);audit(u.id,'Üye yetkisi değiştirildi',id);return json(res,200,{ok:true});}
  if(path==='/api/reset-link'&&method==='POST'){owner(u);const b=await body(req,4096),target=one('SELECT id FROM users WHERE id=?',b.userId);assert(target,404,'Üye bulunamadı.');const raw=token();run('UPDATE resets SET used=1 WHERE userId=?',target.id);run('INSERT INTO resets VALUES(?,?,?,0)',hash(raw),target.id,Date.now()+3600000);audit(u.id,'Şifre yenileme bağlantısı oluşturuldu',target.id);return json(res,201,{url:origin+'/#reset='+raw});}
  if(path==='/api/restore'&&method==='POST'){staff(u);const b=await body(req,4096);assert(['people','photos','events'].includes(b.table),400,'Kayıt türü geçersiz.');run(`UPDATE ${b.table} SET deletedAt=NULL WHERE id=?`,b.id);audit(u.id,'Kayıt geri yüklendi',b.id);return json(res,200,{ok:true});}
  if(path==='/api/settings'&&method==='PATCH'){owner(u);const b=await body(req,16000);for(const key of ['familyTitle','familyStory','mailDomain'])if(key in b){const value=clean(b[key],key==='familyStory'?10000:200);if(key==='mailDomain')assert(!value||/^(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z]{2,}$/i.test(value),400,'Alan adını https:// olmadan yazın.');run('INSERT OR REPLACE INTO settings VALUES(?,?)',key,value);}audit(u.id,'Aile ayarları güncellendi');return json(res,200,{ok:true});}
  if(path==='/api/export'&&method==='GET'){owner(u);return json(res,200,{version:1,exportedAt:now(),settings:settings(),people:all('SELECT * FROM people'),relations:all('SELECT * FROM relations'),photos:all('SELECT * FROM photos'),photoPeople:all('SELECT * FROM photo_people'),events:all('SELECT * FROM events')});}
  return json(res,404,{error:'İşlem bulunamadı.'});
 }
 assert(method==='GET'||method==='HEAD',405,'Yöntem desteklenmiyor.');const file=resolve(publicDir,'.'+decodeURIComponent(path==='/'?'/index.html':path));assert(file.startsWith(publicDir+'/'),404,'Dosya bulunamadı.');const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.webp':'image/webp','.png':'image/png','.woff2':'font/woff2'};const bytes=await readFile(file);res.writeHead(200,{'Content-Type':types[extname(file)]||'application/octet-stream','Cache-Control':extname(file)==='.html'?'no-cache':'public, max-age=3600'});res.end(method==='HEAD'?undefined:bytes);
 }catch(e){if(!res.headersSent)json(res,e.status||(e.code==='ENOENT'?404:500),{error:e.status?e.message:e.code==='ENOENT'?'Dosya bulunamadı.':'İşlem tamamlanamadı. Lütfen tekrar deneyin.'});else res.end();if(!e.status&&e.code!=='ENOENT')console.error(e.message);}
}
const server=http.createServer(handler);server.requestTimeout=30000;server.headersTimeout=10000;server.listen(port,process.env.HOST||'0.0.0.0',()=>console.log(`Sarıçiçek Family: ${origin}`));
setInterval(()=>{run('DELETE FROM sessions WHERE expires<?',Date.now());run('DELETE FROM throttle WHERE expires<?',Date.now());},3600000).unref();
